### ISSUE TITLE
Issues using written parquet file with AWS Athena

### ISSUE THREAD

**Issue by we7313** [elastacloud/parquet-dotnet#111]
Should this tool be capable of creating a parquet file that AWS athena would be able to map a table to?
I created a simple file with just 2 columns and (id, city) and receive the following error when querying from athena:HIVE_CURSOR_ERROR: can not read class parquet.format.PageHeader: null

**Comment by aloneguid** [comment]
@we7313 we are still in alpha therefore bugs are expected :) Could you please give us details which version of parquet-dotnet you are using and code you're using to generate the file?

**Comment by we7313** [comment]
Thanks for getting back to me, I'm cool with this being an alpha - it has great potential.
This is the code I used to create the parquet file:

 var ds = new Parquet.Data.DataSet(
                new SchemaElement<int>("id"),
                new SchemaElement<string>("city")
            );

            ds.Add(1, "London");
            ds.Add(2, "Derby");

            using (Stream fileStream = File.OpenWrite(@"e:\\Download\parquet\1.parquet"))
            {
                using (var writer = new ParquetWriter(fileStream))
                {
                    writer.Write(ds);
                }
            }

I then created a table in athena with 2 columns (id int, city varchar 50).

I get the error: HIVE_CURSOR_ERROR: can not read class parquet.format.PageHeader: null when running a select.

I'd be glad to help out and test more when you need me to.
Also, I get the lastest version every day (Alpha 85) is what I ran on yesterday.

**Comment by aloneguid** [comment]
You're welcome @we7313, it's the people like you who make parquet-dotnet better! :)

here is what I've done so far, generate parquet file with parquet-dotnet:


```csharp
      [Fact]
      public void WriteAthenaSample()
      {
         var ds = new DataSet(
            new SchemaElement<int>("id"),
            new SchemaElement<string>("city"));

         ds.Add(1, "London");
         ds.Add(2, "Derby");

         using (Stream fs = F.Create("c:\\tmp\\athena.parquet"))
         {
            ParquetWriter.Write(ds, fs);
         }
      }

```

and uploaded to S3 bucket. I validate that it can be read with java library to see we are not doing anything unusual and it's fine:

![image](https://user-images.githubusercontent.com/3155189/28176017-d15b0422-67ed-11e7-82a1-585c82ed836b.png).

Essentially this library is used by Apache Spark so we know that the file is readable. I'm new to Athena, so I have a slight problem creating an external table, maybe you can help me?

![image](https://user-images.githubusercontent.com/3155189/28180605-7d7e6276-67fd-11e7-88a8-facc5a73c983.png)

It seems like `access denied`, but I've put the bucket in the same region as Athena, and as a last resort gave permissions to everyone for full access.

**Comment by aloneguid** [comment]
OK I've got the same error as you do now, by creating a table with this script:

```
CREATE EXTERNAL TABLE IF NOT EXISTS pq.test2 (
  `id` int,
  `city` string 
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '1'
) LOCATION 's3://pqtest1/athena/'
TBLPROPERTIES ('has_encrypted_data'='false');
```

Investigating :)

**Comment by we7313** [comment]
Great!  Sorry I couldn't get back to you yesterday (I had one of those days).
BTW, what was the issue with Athena not being able to access the S3 bucket?

**Comment by aloneguid** [comment]
@we7314 no worries :) I'm still investigating this.

The issue with bucket security is slightly unobvious - Athena gives 401 when you specify bucket URL in a form of region i.e. `s3://us-west-2.amazonaws.com/pqtest1/athena/` and shortening it to `s3://pqtest1/athena/` does the trick.

I'm not quite sure how to fix this yet, however I have a working file and almost identical file which causes this issue, therefore digging into the bits to spot the difference.

**Comment by aloneguid** [comment]
@we7313 I've got another error this time, but getting closer :)

![image](https://user-images.githubusercontent.com/3155189/28709947-32d5f7a6-737a-11e7-8b96-2afb77efe6b2.png)

**Comment by aloneguid** [comment]
Still have no idea why Athena doesn't read files, I've raised support issue in AWS forums https://forums.aws.amazon.com/thread.jspa?threadID=260598 and also trying to get this fiddled with myself in the meantime.

**Comment by we7313** [comment]
Thanks for working on this.  This could be a great utility on AWS.

**Comment by aloneguid** [comment]
@we7313  Just letting you know we didn't forget and working on this. I've managed to generate a file with parquet.net similar to a working one with 3 bytes difference. Down from 200 :) It's close...

**Comment by aloneguid** [comment]
@we7313 I've got a working solution, should be in alpha release in a few days

![image](https://user-images.githubusercontent.com/3155189/28974102-1e3fad7e-792d-11e7-8de3-4c704fcfb375.png)

**Comment by we7313** [comment]
Excellent work!

**Comment by aloneguid** [comment]
@we7313 this is I'm the latest alpha now. Feel free to reopen if something is wrong. We have tested to an extent that Athena likes us.

**Comment by we7313** [comment]
It looks like the fix to run in Athena has an issues:
If you take the basic example of creating parquet with elements id & city & change the input
from:
ds.Add(1, "London");
ds.Add(2, "Derby");
to
ds.Add(1, "London");
ds.Add(2, "London");

Athena errors.
It seems that is erroring on  the string column being a duplicate.  This issue does not happen if you have duplicate ints.
