### ISSUE TITLE
Written and read dates differ by one day

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#113]
I've introduced failing tests which prove this is the case. I'm not sure which is the source of truth though - reader or writer :)

**Comment by azurecoder** [comment]
what's the name of the test?

**Comment by aloneguid** [comment]
@azurecoder it in my PR https://github.com/elastacloud/parquet-dotnet/pull/112. If you want to fix it in that branch that's fine too )

**Comment by azurecoder** [comment]
okay, I'll work from that

**Comment by aloneguid** [comment]
@azurecoder that's definitely a writer, the day is off by one after I write with our lib and read with Parquet:

![image](https://user-images.githubusercontent.com/3155189/28203750-e8648f78-6872-11e7-9f08-0451d3635d25.png)
