### ISSUE TITLE
Failing to compress or decompress with snappy

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#115]
Fails on this test scenario:

```csharp
      [Fact]
      public void I_can_write_snappy_and_read_back()
      {
         var ds = new DataSet(
            new SchemaElement<int>("id"),
            new SchemaElement<int>("no"));

         ds.Add(1, 3);
         ds.Add(2, 3);

         var ms = new MemoryStream();
         ParquetWriter.Write(ds, ms, CompressionMethod.Snappy);

         ms.Position = 0;
         DataSet ds1 = ParquetReader.Read(ms);
      }
```

error:
![image](https://user-images.githubusercontent.com/3155189/28214297-98321d7a-68a1-11e7-8ef6-243589b85493.png)

**Comment by sandy-may** [comment]
@aloneguid the issue is the here ``` _snappyCompressor.MaxCompressedLength(uncompressedLength);```

its creates trailing null bytes that cause the length and subsequent decoding to go off. Just got working locally will validate with spark and commit
