### ISSUE TITLE
Compiler error with Tuples 

### ISSUE THREAD

**Issue by azurecoder** [elastacloud/parquet-dotnet#12]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8137	Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference?	Parquet(net451), Parquet(netstandard1.6)	C:\Users\richa\Documents\Projects\parquet-dotnet\src\Parquet\File\Page.cs	84	Active

**Comment by aloneguid** [comment]
Hi @azurecoder try to do nuget restore on the solution. System.ValueTuple comes as extra nuget package for C# 7.

**Comment by azurecoder** [comment]
Ah, perfect, told you I was old school!
