### ISSUE TITLE
Open in Excel

### ISSUE THREAD

**Issue by azurecoder** [elastacloud/parquet-dotnet#130]
Might not be possible but build an extension of some kind so that Excel can read in parquet

**Comment by aloneguid** [comment]
It's hard if possible at all to make excel read custom file formats.

We can probably have a toolbar button which opens a dialog to read the file and puts content into current worksheet, if that's acceptable.

However, in general writing Office extensions is hard, and really hard when you want to support multiple versions of Office.

**Comment by azurecoder** [comment]
Closed, moved to new repo by @AndyCross /elastacloud/parquet-excel
