### ISSUE TITLE
Measure performance for writing different parquet types

### ISSUE THREAD

**Issue by azurecoder** [elastacloud/parquet-dotnet#133]
Currently all columns use plain encoding to write parquet out but there are performance hits on certain types, CPU measures and times need to be recorded for each column write.
@aloneguid to put a richer description of needs here

**Comment by xhochy** [comment]
In Parquet-cpp development I saw a clear advantage of dictionary encoding. It was not much more CPU time but the compression rates on most data did speed up things a lot as it reduced I/O significantly.

**Comment by xhochy** [comment]
You might also take a look at my blog post https://tech.blue-yonder.com/efficient-dataframe-storage-with-apache-parquet/ where I did some comparisons of the compression algorithms of Parquet, note that they are all based on dictionary encoded columns, plain encoded columns always were larger and only in the case of uncompressed files were they faster to read/write.

**Comment by azurecoder** [comment]
Thanks @xhochy this is really useful so you would suggest dictionary or run-length encoding for high incidence of repetitions?

**Comment by xhochy** [comment]
Yes, I would suggest that. In `parquet-cpp` (and the same is possibly also true for `parquet-mr`), we use dictionary encoding (which also then applies hybrid-bitpacking-runlength-enconding on the indices) by default and only revert back to plain encoding if the dictionary gets larger than a certain threshold of values.

**Comment by aloneguid** [comment]
will be part of #171
