### ISSUE TITLE
Support reading the Creator of the file

### ISSUE THREAD

**Issue by AndyCross** [elastacloud/parquet-dotnet#136]
In order to make Parq feature consistent with parquet-tools we need to support the _meta_ command which outputs some metadata that is currently not surfaces:

**File.Creator**

![image](https://user-images.githubusercontent.com/773613/28511245-4e4a1cee-7044-11e7-9f01-149c34bb0ef5.png)

**Comment by AndyCross** [comment]
I think this is given to use in: Thrift.FileMetaData.Created_by but this is not exposed 

https://github.com/elastacloud/parquet-dotnet/blob/master/src/Parquet/Data/Schema.cs#L24

**Comment by aloneguid** [comment]
We populate `creator` according to specs when writing files but yeah, it's not exposed anywhere. This can be done as a **read-only** property on DataSet. If anyone grabs this before myself - don't expose it for writing as it must be filled in according to specs.
