### ISSUE TITLE
Support parquet-tools rowcount

### ISSUE THREAD

**Issue by AndyCross** [elastacloud/parquet-dotnet#137]
A simple feature that returns solely the rowcount of a parquet file 

![image](https://user-images.githubusercontent.com/773613/28511490-59ad9524-7045-11e7-9334-d50269a0bb3a.png)

**Comment by aloneguid** [comment]
You mean without reading the file? Because DataSet has `.Count` property

**Comment by AndyCross** [comment]
This is completed work.

It meant in parq specifically.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
