### ISSUE TITLE
Create comparison chart Parquet.Net vs parquet-mr vs fastparquet vs parquet-cpp

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#171]
Compare read and write speed on different file sizes.

Adding more thoughts here. Every framework can be a console util callable from command line.

Input: `mode` `filename`
where mode is `read` or `write`. With write it would make sense to have an extra parameter specifying a number of rows to write. Apparently all utils should use the same schema and data to achieve fair estimations.

Output: `time` it took to do the operation. This should be returned by the util, because we don't want to include initialisation and warmup time, so each util has to measure it independently.

This should be collected by our console program (theres `ParquetRunner` in the solution). and print numbers in the console.

Later on we can submit those numbers to `Azure AppInsights` and maybe even run on scheduled basis so we can track relative performance over time.

**Comment by xhochy** [comment]
Please also include parquet-cpp/pyarrow as this is probably the fastest implementation at the moment for a lot of cases, see also http://wesmckinney.com/blog/python-parquet-update/

**Comment by azurecoder** [comment]
Thanks @aloneguid @xhochy we're very interested in Arrow so this is a good opportunity to get hands on. We'll publish our comparison hopefully at some point next week.

**Comment by martindurant** [comment]
For fastparquet, it's worth pointing out firstly, that the use case is somewhat tuned to pandas-like data, and secondly, that fastparquet will often read faster data which was written by fastparquet.

**Comment by aloneguid** [comment]
always pending!
