### ISSUE TITLE
Add statistics to column chunk and page header

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#177]
Both support embedding following stats:
- Min
- Max
- Null Count
- Distinct Count

Not essential, but useful to have as those help choosing the best encoding for writing for example. Also can skip calculating on the whole dataset.

**Comment by xhochy** [comment]
The main use case for these statistics is in predicate pushdown of a query over a Parquet dataset. Most engines (Presto, Impala, Drill,...) will use them to determine whether to read a Page/ColumnChunk. The most important statistics here are min and max.
