### ISSUE TITLE
Add JSON adapter

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#180]
Same way as `CSV` is implemented we can support `JSON` as an input and output format.

**Comment by we7313** [comment]
It would be great to be able to infer a schema from a json file or to be able to provide a jsonschema file to build the parquet schema.

**Comment by aloneguid** [comment]
@we7313 we've moving this out of the project as it's not related to parquet format, better solve one problem well ) We'll publish something soon as a separate package.
