### ISSUE TITLE
Decimal .NET type support

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#189]
Requires some sort of annotation.

**Comment by aloneguid** [comment]
@azurecoder the code is fine as Spark reads this with no problem, I'm not sure however how to choose scale and precision when writing. The problem is that both can be specified only once per column, however you can have many numbers where one scale doesnt fit all, so if value range is vast there will be some lose of precision.

**Comment by dmitryPavliv** [comment]
@aloneguid are you guys plan to add support for specifying scale / precision in schema definition? as I understood it is hardcoded now 
`var bd = new BigDecimal(d, 38, 18);`

**Comment by aloneguid** [comment]
@dmitryPavliv you're correct it's hardcoded. I don't quite understand yet how to detect best precision/scale unless you specify it manually. The problem is that these two have to be set per column, not on individual values.

**Comment by aloneguid** [comment]
@xhochy maybe you can kindly advise?

**Comment by dmitryPavliv** [comment]
yes, we need to set it on column basis and from my understanding it should be done in `new SchemaElement<decimal>("dec")` or derived from it class

**Comment by aloneguid** [comment]
@dmitryPavliv I think you're right, however when doing work in Scala I don't have to specify scale/precision, i.e.

```scala
val decimalSample: BigDecimal = 100000000.5 //precision - 10, scale - 1
val decimalSample2: BigDecimal = 0.0000000005 //precision - 2, scale - 11
```

then by writing to parquet:

```scala
val df = sc.parallelize(Seq(
   (1, decimalSample),
   (2, decimalSample2)
)).toDF("id", "decimal")
```

I get the following schema back:

```
root
|-- id: integer (nullable = true)
|-- decimal: decimal(38,18) (nullable = true)
```

so somehow it thinks that precision is 38 and scale is 18, which is what remains a mystery so far.

**Comment by aloneguid** [comment]
opened #209 for this

**Comment by xhochy** [comment]
@aloneguid I have no idea how the Scala code actually comes to the precision but in Parquet the precision and scale are part of the schema and does global on a per file basis.

Also be aware that the choice of PhysicalType used for storing the decimals depends on the chosen precision as outlined in the spec: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#decimal

**Comment by aloneguid** [comment]
.NET BCL doesn't have BigDecimal implementation unfortunately (only BigInteger)  and nothing alternative to Java's BigDecimal. System.Decimal is somewhat more limited than BigDecimal and I believe mapping from C# decimal to Parquet can have hardcoded precision/schema, however I didn't work it out perfect.

I see BigDecimal support possible by introducing a new type, or using some well-known library which provides this, need to think about it.

**Comment by dmitryPavliv** [comment]
@aloneguid agree, c# doesn't have BigDecimal, but here is my use case: I have table in Impala with decimal columns and I want to save data from my .net app. For example my table has columns with decimal (17,12). If I will use hardcoded scale / precision for serialization like (38,18) Impala won't recognize this parquet file as it expects (17,12) which has different data size as was correctly pointed out above.

**Comment by aloneguid** [comment]
@dmitryPavliv that's a good use case, thanks. The only way to do  that is add a custom type then. It doesn't work as we always use FIXED_LENGTH_BYTE_ARRAY for decimal, whereas Parquet needs INT64 for precision <= 18 and INT32 for precision <= 9. 

Are you using `decimal` in C# to represent your data at the moment?

**Comment by dmitryPavliv** [comment]
yes, we're using decimal in c#. Currently we have odd flow because of luck of .net parquet serializer:
1) we serialize our data in AVRO format (dates are stored as BIGINT, decimals are stored as STRING - this is how microsoft implementation of AVRO serializer works)
2) we save AVRO files to HDFS in stage database
3) we execute script to convert AVRO to PARQUET on Impala side
`INSERT INTO parquet_table SELECT CAST(decimal_column AS DECIMAL(17,12)), another_column FROM avro_table`

so c# decimal is enough for our needs but what I want to do is to remove steps 1-3 and substitute them with saving PARQUET file directly. It would be great to have ability to specify scale / precision for regular c# decimal type so it will be serialized correctly and recognized by Impala

**Comment by aloneguid** [comment]
thanks @dmitryPavliv  for detailed explanation, we should be able to add it some time this week

**Comment by aloneguid** [comment]
@dmitryPavliv this is in out latest alpha if you want to check it out and see if it works for you. This is how it's done today - https://github.com/elastacloud/parquet-dotnet/blob/master/doc/types/floating.md

**Comment by dmitryPavliv** [comment]
@aloneguid perfect! we will test
