### ISSUE TITLE
JSON.NET integration

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#19]
Comes as a separate package? Should support reading from a JSON document in a form that can be written to Parquet. Same for converting back from nested parquet to JSON.

**Comment by azurecoder** [comment]
@aloneguid was thinking that this should reside on the dataframe using a provider model? Maybe csv/json/xml to parquet?

**Comment by aloneguid** [comment]
@azurecoder good idea. I'm already reading CSV into `DataSet` for testing i.e. to compare with parquet reader. We can make it in a form of extension methods to DataSet, like 

`DataSet.FromCsv(stream, schema)`
`DataSet.ToCsv(stream)`

etc.?

**Comment by aloneguid** [comment]
I think this is outside of this library's scope.
