### ISSUE TITLE
Int64 .NET type support

### ISSUE THREAD

**Issue by dmitryPavliv** [elastacloud/parquet-dotnet#194]
can you guys add support for Int64 (BIGINT) datatype?

**Comment by aloneguid** [comment]
@simoco should be trivial to implement, we already have code to write Int64, it's just not covered in tests yet and therefore not exposed.

**Comment by dmitryPavliv** [comment]
@aloneguid thanks, waiting for the release

**Comment by aloneguid** [comment]
@dmitryPavliv it's available in the latest alpha, please check if it works for you.

**Comment by dmitryPavliv** [comment]
@aloneguid thanks, it works
