### ISSUE TITLE
Integrationtests with Apache Parquet-cpp/mr

### ISSUE THREAD

**Issue by xhochy** [elastacloud/parquet-dotnet#195]
It would be nice to have cross checking between various parquet implementations. 

As a reference we could use the setup Apache Arrow is using to crosscheck its different implementations.

**Comment by aloneguid** [comment]
@xhochy @azurecoder we're working on performance comparison framework using all the popular libs (parquet-mr, fastparquet, parquet-cpp) which should be a base for better integration testing.

**Comment by aloneguid** [comment]
unfortunately won't happen any time soon
