### ISSUE TITLE
Implement reader for plain encoding

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#2]
I've started a draft implementation in File.PEncoding.ReadPlain but that only works for Boolean/int32.

Encoding docs - https://github.com/Parquet/parquet-format/blob/master/Encodings.md#plain-plain--0

**Comment by aloneguid** [comment]
Hi @azurecoder, I've integrated all the types, only FIXED_LEN_BYTE_ARRAY left to do. I can't find a sample encoded in this though.

**Comment by azurecoder** [comment]
Hey @aloneguid looking at this today - will follow the spec for this
