### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#20]
There is a considerable amount of I/O therefore Async support will be beneficial on both ParquetReader and ParquetWriter.

BinaryWriter/BinaryReader don't support Async operations, therefore this might mean we need to implement primitive type unpacking ourselves.

**Comment by aloneguid** [comment]
Thrift libs also don't support Async operations. Closing as this might be too much work.

**Comment by georgiosd** [comment]
Can you please explain what would be necessary for async support?

**Comment by aloneguid** [comment]
@georgiosd I'm not quite sure at the moment. We need to decide what's the most effective way to apply Async inside the library. Marking all I/O operations with Async will actually make it slower as there are a lot of micro reads happening on low level which at the moment is using standard .net memory buffers. Every Async call introduces a delay for Async state machine context switching, therefore there should be some clever balance.

**Comment by aloneguid** [comment]
I don't seriously have statistics and will only rely on your feedback) having some decent stats will involve data collection which is hard to do legally from a library. Most of our own projects write massive amounts of data and this is done via constant append operations. We just keep the steam open and keep calling write method with next chunk of data. What's your use case?

**Comment by georgiosd** [comment]
Same as yours but my code snippet doesn't seem to work.

Can you share an example?

**Comment by aloneguid** [comment]
@georgiosd yes sure, you can find examples in https://github.com/elastacloud/parquet-dotnet/blob/master/src/Parquet.Test/ParquetWriterTest.cs in tests starting with "Append_". We are working on a better write streaming support in major V3, I hear you ;)
