### ISSUE TITLE
Merge schemas and rows

### ISSUE THREAD

**Issue by we7313** [elastacloud/parquet-dotnet#203]
It would be nice to implement a merge method, like system.data.dataset has.
Right now if I need to roll up many smaller parquet files I need to open each file and iterate through it row by row.  An optimized approach would be great.

**Comment by aloneguid** [comment]
@we7313 as `DataSet` implements `IList<Row>` you can simply do `ds1.AddRange(ds2)` - that will do merge if schemas match. Or would you expect merge method to also merge schemas?

**Comment by we7313** [comment]
AddRange is exactly what I was looking for thanks!

**Comment by aloneguid** [comment]
@we7313 you're welcome. I think a method which can also merge schemas would be extremely useful so I'll keep this open.

**Comment by azurecoder** [comment]
@aloneguid picking this up. Spark does this seamlessly would be good to do this too.

**Comment by azurecoder** [comment]
Adding a merge method to DataSet but will talk through with you. Spark does seamlessly looking at directory of parquet files. Longer term this might be better. Worth discussing whether parquet-dotnet is the right place for this.

**Comment by we7313** [comment]
It seems that the AddRange functionality has been removed in the more recent builds.  I know this was last available in the 1.4 builds, but is no longer available in the 1.5 builds.  I use this to take smaller parquet files and roll them up into a bigger file (with the same schema).

**Comment by aloneguid** [comment]
@we7313 1.5 is still in preview, there are a few breaking changes, can you open a new issue please ;)
