### ISSUE TITLE
Unable to target .NET Framework 451

### ISSUE THREAD

**Issue by AndyCross** [elastacloud/parquet-dotnet#204]
Parquet-dotnet ships to nuget and supports .NET Framework 451, but its dependency Snappy.Sharp only targets .NETStandard=v1.1

When trying to use with .NET Framework 451, there is an error:
![image](https://user-images.githubusercontent.com/773613/29683575-c1918c20-8906-11e7-9fee-bf429f930184.png)

**Comment by aloneguid** [comment]
Which framework is the main project targeting?

**Comment by AndyCross** [comment]
4.5.1 

Attempting to gather dependency information for package 'Parquet.Net.1.1.128' with respect to project '1.BlobAbstractions\BlobAbstractions.ADLS', targeting '.NETFramework,Version=v4.5.1'

**Comment by AndyCross** [comment]
If you install Snappy.Sharp first, then Parquet.Net this succeeds.

**Comment by aloneguid** [comment]
Snappy.Sharp doesn't seem to be maintained. The solution i see is either fork it off and fix the build or find an alternative library. @sandy-may are you up for this? )

**Comment by sandy-may** [comment]
yeah I will look at forking it out over the weekend and getting up to scratch

**Comment by softeering** [comment]
Just faced this issue on my side and while trying to add the NuGet ref to Snappy.Sharp, I found this:
https://snappy.machinezoo.com/

You probably already saw this but just in case

**Comment by AndyCross** [comment]
hey @softeering I managed to get around this by first installing the Snappy.Sharp independently of parquet-dotnet. There's a little weirdness in the dependencies which we still have to solve.

Thanks

**Comment by softeering** [comment]
Thanks @AndyCross I saw your comment, which actually did the trick.
Mine was more about changing Snappy.Sharp with something else (from @aloneguid)

**Comment by aloneguid** [comment]
We were thinking of dropping support for .NET 4.5 and targeting .NET Standard 1.4 only (which is supported in .NET 4.6). I wonder if there are any use cases actually requiring .NET 4.5?

**Comment by softeering** [comment]
I wouldn't mind dropping support for .NET 4.5 but that's a personal opinion.
On another point, I added the nuget references to an existing app (ASP.NET 4.6.1, EF 6...) and the .NET standard packages "broke everything" (issues with references)

Why does Parquet.NET require pakages such as Kestrel? ASP.NET Core and others?
I simply wanted to be able to generate a parquet file from System.Data.DataTable but it seems the library has a lot of dependencies.

Thanks

**Comment by aloneguid** [comment]
@softeering unfortunately this is due to a problem with Apache Thrift dependency. Stupidly enough Apache Thrift references Kestrel library and a few more as in #207. I've already raised the issue in Thrift Jira and working on a .net standard port with zero dependencies.

**Comment by softeering** [comment]
@aloneguid got it thanks
I didn't have a deeper look at Apache Thrift. That's unfortunate, I won't be able to use Parquet.NET until this gets cleaned. I'll have a look at the apache-thrift lib to try to understand these dependencies.

**Comment by dmitryPavliv** [comment]
@aloneguid if possible let's not drop support for .NET 4.5 as a lot of projects are still using it and you will just "cut audience" for single available .Net library for Parquet. Don't kill the hope:)

**Comment by aloneguid** [comment]
@dmitryPavliv  is there any reason you can't use .NET 4.6? Just wondering, i'll keep 4.5 if it's required by anyone.

**Comment by dmitryPavliv** [comment]
Well, I'm working on a big platform (30+ teams) and changing target framework need to be done for all projects. All build servers must be adjusted as well. It will require a lot of time and coordination which makes this task highly expensive. As usual on big project it is not always possible to be on trend :)

**Comment by aloneguid** [comment]
@dmitryPavliv I understand 👍 Just compiled a custom Thrift build with zero dependencies and kept .net 4.5.1 as a target, this should resolve an issue for @softeering  as well. I'll post here when a new build is ready.

**Comment by aloneguid** [comment]
![image](https://user-images.githubusercontent.com/3155189/30331839-bd42cafc-97d0-11e7-9f5f-0e29e0976868.png)

**Comment by dmitryPavliv** [comment]
@aloneguid you're the best!

**Comment by aloneguid** [comment]
@dmitryPavliv @softeering v1.3 just went live, with most dependencies stripped out. As always thanks for contributing to parquet.net guys ;)

**Comment by softeering** [comment]
Thanks to you guys for the quick turnaround
Will have a look asap

**Comment by softeering** [comment]
Just as an FYI
I managed to reference Parquet.NET without any issue in my existing 4.6 app
Thanks again guys
