### ISSUE TITLE
Support decimals with different precisions

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#209]
At the moment precision and scale is hardcoded as I didn't understand how to choose it best automatically. This should be allowed to be specified in schema or detected same way parquet-mr does.

See https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#decimal for more.

Please see #189 for discussion and details.

**Comment by aloneguid** [comment]
@dmitryPavliv just wondering if you had a chance to check this out ;)

**Comment by dmitryPavliv** [comment]
Hi @aloneguid . Yep, we've checked. But unfortunately we're receiving error

`Bad status for request TFetchResultsReq(fetchType=0, operationHandle=TOperationHandle(hasResultSet=True, modifiedRowCount=None, operationType=0, operationId=THandleIdentifier
(secret='\x04N\xd1\\\r\xdeGG\x00\x00\x00\x00\xd5\xd1\xa7"', guid='\x04N\xd1\\\r\xdeGG\x00\x00\x00\x00\xd5\xd1\xa7"')), 
orientation=4, maxRows=100): TFetchResultsResp(status=TStatus(errorCode=None, errorMessage="\nFile 
'hdfs://nameservice1/user/hive/warehouse/test.db/test_0/column1=1/column2=1/test.parquet' 
has an incompatible Parquet schema for column 'test.test_0.decimalfield'. 
Column type: DECIMAL(17,5), Parquet schema:\nrequired int64 decimalfield [i:9 d:0 r:0]\n", sqlState='HY000', 
infoMessages=None, statusCode=3), results=None, hasMoreRows=None)`

**Comment by aloneguid** [comment]
@dmitryPavliv can you attach the parquet file and code used to generate it here? I can't see anything obvious yet.

**Comment by nzapolski** [comment]
Hi @aloneguid . Let me show parquet file with such problem. 
[parquet.zip](https://github.com/elastacloud/parquet-dotnet/files/1264700/parquet.zip)
Class to serialize 
```
public class Test_0
{
    public int Id { get; set; }
    public decimal DecimalField { get; set; }
}
``` 

Schema for it
```
new SchemaElement<int>("id"),
new DecimalSchemaElement("decimalField", 17, 5),
```

Table
```
CREATE TABLE Test_0 (
  id INT,
  decimalField DECIMAL(17,5)
)
STORED AS PARQUET;
```
Error message

> File 'hdfs://nameservice1/user/hive/warehouse/test.db/test_0/test.parquet' has an incompatible Parquet schema for column 'test.test_0.decimalfield'. Column type: DECIMAL(17,5), Parquet schema:
> required int64 decimalField [i:1 d:0 r:0]
>

**Comment by aloneguid** [comment]
@dmitryPavliv @nzapolski thank you, I can read the file with both parquet.net and parquet-mr (Java) with no problem. I'm not quite sure why Impala doesn't read decimal yet, however this message "has an incompatible Parquet schema" tell me that Impala has some special rules around that not compatible with parquet specs. I'll investigate.

**Comment by aloneguid** [comment]
@dmitryPavliv  @nzapolski I found the problem, looks like Impala only understands one encoding for decimals as described in https://issues.apache.org/jira/browse/SPARK-20297 whereas there are 3 encodings Parquet spec supports for decimals. Parquet.Net lib switches between them based on precision number, so we have to add some impala compatibility switch. I should come back to this on Monday.

**Comment by aloneguid** [comment]
@dmitryPavliv @nzapolski  so I couldn't wait and just done it. In the latest alpha 1.2.0-alpha-137) there is an optional parameter `DecimalSchemaElement(string name, int precision, int scale, bool forceByteArrayEncoding = false)` which when set to true will write decimals so they are compatible with Hive and Impala. I wonder if you can try it as I don't have impala nearby.

**Comment by nzapolski** [comment]
@aloneguid Great work! Now select query works fine via Hive. But we faced another problem via Impala:

> File 'hdfs://nameservice1/user/hive/warehouse/test.db/test_0/test.parquet' column 'DecimalField' has an invalid type length. Expecting: 8 len in file: 16

**Comment by dmitryPavliv** [comment]
@aloneguid please refer to Impala docs for details https://www.cloudera.com/documentation/enterprise/5-6-x/topics/impala_decimal.html

![image](https://user-images.githubusercontent.com/8275275/29920357-d26b4b90-8e55-11e7-8613-da946a09da53.png)

**Comment by aloneguid** [comment]
Hi @dmitryPavliv sorry just got to this issue. I've added the byte array size correction for Impala, it's in the latest alpha (138)

**Comment by dmitryPavliv** [comment]
hey @aloneguid , works perfectly! thanks

**Comment by aloneguid** [comment]
@dmitryPavliv thank you for the patience ;)
