### ISSUE TITLE
Document that nulls are always allowed

### ISSUE THREAD

**Issue by alexdeng** [elastacloud/parquet-dotnet#217]
Why is primitive nullable types not supported (exception thrown in the code specifically for this case)?
parquet spec won't encode null but can support columns with null values in definition levels. Any plan to support primitive nullable columns?

**Comment by aloneguid** [comment]
@alexdeng they are supported, in a way. `ParquetSchema<T>` always accepts a non-nullable type like `int`, `long` etc., however any value in parquet dataset is allowed to be null. When we write the file and find a null value, the underlying internal parquet structures will include appropriate schema and definition levels are written as well. We didn't want to make a distinction between nullable and non-nullable types as it's much easier to just specify underlying type.

**Comment by aloneguid** [comment]
@alexdeng also shifting this decision to parquet library allows us to minimize space used i.e. when you don't include any nulls there is no need to write definition levels and file becomes smaller.
