### ISSUE TITLE
ParquetReader fails on column consisting null values only

### ISSUE THREAD

**Issue by nzapolski** [elastacloud/parquet-dotnet#222]
[parqet.zip](https://github.com/elastacloud/parquet-dotnet/files/1302963/parqet.zip)
I have problem with reading parquet file with table that contains column with NULL values only.

Failed on line
`if (indexes == null) throw new ParquetException("dictionary has no attached index");`

```
Parquet.File.ValueMerger.ApplyDictionary(System.Collections.IList dictionary, System.Collections.Generic.List<int> indexes, int maxValues) Line 46
Parquet.File.ValueMerger.Apply(System.Collections.IList dictionary, System.Collections.Generic.List<int> definitions, System.Collections.Generic.List<int> repetitions, System.Collections.Generic.List<int> indexes, int maxValues) Line 32
Parquet.File.PColumn.Read(long offset, long count) Line 95
Parquet.ParquetReader.Read() Line 146
```

Example file is attached.

Thank you!

**Comment by aloneguid** [comment]
thanks @nzapolski I'll fix this rather soon )

**Comment by aloneguid** [comment]
@nzapolski  forgot to mention the fix is available in latest alpha :)

**Comment by dmitryPavliv** [comment]
@aloneguid thanks, it works. You can close the issue

**Comment by aloneguid** [comment]
Thanks @dmitryPavliv

**Comment by nzapolski** [comment]
Thank you @aloneguid !
