### ISSUE TITLE
Need support for complex parquet objects

### ISSUE THREAD

**Issue by we7313** [elastacloud/parquet-dotnet#223]
Is a complex object like below able to be created with parquet.net?

{
	"Message": {
		"id": "0c04a8c6-eada-45b4-ac95-4e59672d0db8",
		"Timestamp": "2017-09-14T14:27:47.4356142Z",
		"Name": "App Name",
		"TransactionName": "PL",
		"AdditionalInfo": [{
			"Id": "User",
			"Value": "some value",
			"IsDebug": false
		}]
	}
}

**Comment by aloneguid** [comment]
@we7313 potentially yes, however not at the moment. There is code which partially implements nested structures, arrays and repeated fields, however it's parked at the moment as it requires a lot of testing. We are planning to release this eventually, however it's not a priority at the moment.

**Comment by aloneguid** [comment]
@we7313 just wondering what's your use case for this? We couldn't find any useful application for nested structures hence the work was parked.

**Comment by we7313** [comment]
Thanks for asking.  I believe I have an excellent use case.
I'd like to be able serialize any object, put a parquet schema on it and put it in S3.
I then I would map an Athena table to it.  This object would now be query able while residing in S3, while not needing to maintain a database instance.  I could use this to capture change and basically create a real time event streaming repository.
I know I don't need parquet to achieve this, but the advantages are huge as far as query performance and size of space used in s3.
Interested in your thoughts on this...

**Comment by aloneguid** [comment]
@we7313 I hear you. Unfortunately we're at least a few weeks away from getting this done. There is a set of interesting permutations in parquet schema to support this fully.

**Comment by aloneguid** [comment]
@we7313 created an issue #226 to track this. Hopefully will roll out gradually in different releases.
