### ISSUE TITLE
Support nested structures 

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#226]
This is a container to group all issues that finish nested structures support:

- [x] #225 - repeated fields
- [x] #227 - nested non-repeated structures
- [x] #228 - repeated fields in nested structures
- [x] repeated structures
  - [x] read
  - [x] write
- [x] repeated structures in nested structures
  - [x] read
  - [x] write
- [x] compatibility tests

old parked issues: #187, #188

**Comment by akatz0813** [comment]
Will a MAP be considered a nested structure?  If not, I'll open a request for it.    We need to serialize a string, string dictionary that are customer defined attributes that can change on each entry.

**Comment by aloneguid** [comment]
@akatz0813 sorry no, it will be an embedded type as per https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#maps. I've raised #255 however we don't have any estimates when this will be done. Always happy to get help ;)

As a workaround you can always use a json document serialised into a string.

**Comment by akatz0813** [comment]
@aloneguid is there a guide or primer to implementing new types? Or even a list of areas that require changes. I believe I can get someone ok my team to contribute.

**Comment by aloneguid** [comment]
This is working now, still testing for compatibility with Impala and Spark though.

**Comment by DSKunjwal** [comment]
@aloneguid we are eagerly waiting for nested structure support, is it released or soon to be realeased, please guide. Thanks
