### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by nzapolski** [elastacloud/parquet-dotnet#229]
We have a 250Mb parquet file with 20M records.
Speed of reading of this file is too slow. The main problem is memory consumption.

In the middle of DataSet creation (at processing 10 millionth row) in call
`DataSet ds = merger.Merge(pathToValues);`
we have 25Gb of allocated RAM.

As a result we have long pauses in processing the rest of records due to GC.
What can you advice us in this situation?

Thank you!

**Comment by aloneguid** [comment]
Hi @nzapolski, that's a really big file in parquet terms. Have you tried paging through the source file, you can pass `ReaderOptions` and set `offset` and `count`.
