### ISSUE TITLE
short type is missing

### ISSUE THREAD

**Issue by nzapolski** [elastacloud/parquet-dotnet#235]
Hello!
Is it possible to add `short` type?

**Comment by aloneguid** [comment]
Yes definitely. Should be there some time next week.

**Comment by aloneguid** [comment]
@nzapolski by the way are you interested in contributing? I'm happy for you to do this fix.

**Comment by nzapolski** [comment]
I will be happy to do this!

**Comment by aloneguid** [comment]
@nzapolski thanks, assigned to you )
