### ISSUE TITLE
BigDecimal constructor throws OverflowException for large decimal values

### ISSUE THREAD

**Issue by moggy001** [elastacloud/parquet-dotnet#239]
The following constructor throws an exception...

```
public BigDecimal(decimal d, int precision, int scale)
      {
         OriginalValue = d;
         Precision = precision;
         Scale = scale;

         decimal value = d;
         while (scale-- > 0) value *= 10m;
         Value = value;
      }

```
If d = 83086059037282.54 and precision = 38 and scale = 16 then the scaled version of the decimal value cannot be calculated and throws an exception at System.Decimal.FCallMultiply().
My dataset holds the value in a column of type DecimalSchemaElement.
Easy to replicate with other values of d greater than 79000000000000 when scale is 16.

**Comment by moggy001** [comment]
I took a zip of the current master branch and copied it to my local and referenced that in my code.
To fix the problem (and probably a few other potential bugs) I altered the BigDecimal class to the following:

``
    struct BigDecimal
    {
        /// <summary>
        /// Contains a Decimal value that is the big integer
        /// </summary>
        public decimal DecimalValue { get; private set; }

        public BigInteger UnscaledValue { get; private set; }

        /// <summary>
        /// The scale of the decimal value
        /// </summary>
        public int Scale { get; set; }

        /// <summary>
        /// The precision of the decimal value
        /// </summary>
        public int Precision { get; set; }

        public BigDecimal(byte[] data, Thrift.SchemaElement schema)
        {
            data = data.Reverse().ToArray();

            UnscaledValue = new BigInteger(data);
            Precision = schema.Precision;
            Scale = schema.Scale;

            var scaleMultiplier = BigInteger.Pow(10, Scale);
            var fpUnscaled = default(BigInteger);
            var ipScaled = (decimal)BigInteger.DivRem(UnscaledValue, scaleMultiplier, out fpUnscaled);
            var fpScaled = (decimal)fpUnscaled / (decimal)scaleMultiplier;

            DecimalValue = ipScaled + fpScaled;
        }

        public BigDecimal(decimal d)
        {
            uint[] bits = (uint[])(object)decimal.GetBits(d);

            decimal mantissa =
               (bits[2] * 4294967296m * 4294967296m) +
               (bits[1] * 4294967296m) +
               bits[0];

            uint scale = (bits[3] >> 16) & 31;

            uint precision = 0;
            if (d != 0m)
            {
                for (decimal tmp = mantissa; tmp >= 1; tmp /= 10)
                {
                    precision++;
                }
            }
            else
            {
                // Handle zero differently. It's odd.
                precision = scale + 1;
            }

            DecimalValue = d;
            Precision = (int)precision;
            Scale = (int)scale;

            var scaleMultiplier = BigInteger.Pow(10, Scale);
            var ipScaled = new BigInteger(DecimalValue);
            var fpScaled = DecimalValue - (decimal)ipScaled;
            var fpUnscaled = fpScaled * (decimal)scaleMultiplier;

            UnscaledValue = (ipScaled * scaleMultiplier) + new BigInteger(fpUnscaled);
        }

        public BigDecimal(decimal d, int precision, int scale)
        {
            DecimalValue = d;
            Precision = precision;
            Scale = scale;

            var scaleMultiplier = BigInteger.Pow(10, Scale);
            var ipScaled = new BigInteger(DecimalValue);
            var fpScaled = DecimalValue - (decimal)ipScaled;
            var fpUnscaled = fpScaled * (decimal)scaleMultiplier;

            UnscaledValue = (ipScaled * scaleMultiplier) + new BigInteger(fpUnscaled);
        }

        /// <summary>
        /// Converts a BigDecimal to a decimal
        /// </summary>
        /// <param name="bd">The BigDecimal value</param>
        public static implicit operator decimal(BigDecimal bd)
        {
            return bd.DecimalValue;
        }

        private byte[] AllocateResult()
        {
            int size;

            //according to impala: https://www.cloudera.com/documentation/enterprise/5-6-x/topics/impala_decimal.html

            if (Precision <= 9)
                size = 4;
            else if (Precision <= 18)
                size = 8;
            else
                size = 16;

            return new byte[size];
        }

        public byte[] ToByteArray()
        {
            byte[] result = AllocateResult();

            byte[] data = UnscaledValue.ToByteArray();

            if (data.Length > result.Length) throw new NotSupportedException($"decimal data buffer is {data.Length} but result must fit into {result.Length} bytes");

            Array.Copy(data, result, data.Length);

            result = result.Reverse().ToArray();
            return result;
        }
    }

**Comment by azurecoder** [comment]
Hi @moggy001 can you generate a PR for this it's easier for us to diff and credit you with the changes. Can you also ensure that you have an up-to-date unit test in the tests project. Thanks for the contribution!

**Comment by aloneguid** [comment]
I've integrated this in the latest alpha. Shame PR wasn't raised.

**Comment by moggy001** [comment]
Thanks Ivan. Unfortunately, I have never contributed to an open project before and I simply didn't get time to figure how to do so in between my regular work. I have other changes/ fixes that I think should be applied to this library so I shall try to raise a pull request for those.

**Comment by aloneguid** [comment]
@moggy001 no worries, i understand. You code sample is brilliant and was easy to integrate ;)
