### ISSUE TITLE
Impala decimal size issue

### ISSUE THREAD

**Issue by kRaBby** [elastacloud/parquet-dotnet#243]
![image](https://user-images.githubusercontent.com/3025564/31602921-234f272c-b267-11e7-8f33-f11d6abf9511.png)
http://impala.io/doc/html/parquet-common_8h_source.html
![image](https://user-images.githubusercontent.com/3025564/31602973-5c28ccd8-b267-11e7-80ec-7c5a5844c488.png)
https://www.cloudera.com/documentation/enterprise/5-6-x/topics/impala_decimal.html
Impala documentation and source code contradicts to each other and decimal type can has almost any bytearray size. Can it be fixed?

**Comment by nzapolski** [comment]
I can take this issue

**Comment by aloneguid** [comment]
@nzapolski you're welcome to :)

**Comment by aloneguid** [comment]
@kRaBby - @nzapolski has fixed this, can you please check it's working for you in latest alpha?

**Comment by kRaBby** [comment]
It works. Thanks.
