### ISSUE TITLE
DateTime should not be allowed as SchemaElement type?

### ISSUE THREAD

**Issue by grbinho** [elastacloud/parquet-dotnet#247]
While trying to append to a file, I ran into an issue with using `DateTime` as a type of `SchemaElement<T>`.
The code below will throw an exception:
`Parquet.ParquetException: 'DataSet schema does not match existing file schema'`

This is because `DateTime` schema is stored as `INT96`. When appending to file, original schema is read and INT96 is interpreted as `DateTimeOffset`. It's not possible to know which type was initially used as both `DateTimeOffset` and `DateTime` are stored as `INT96`.

Does it make sense to remove `DateTime` from the list of `allTypePrimitives` in TypePrimitive.cs or to have a `CovertedType` for this case?

````C#
 [Fact]
      public void Append_shoud_work()
      {
         var schema = new Schema();
         schema.Elements.Add(new SchemaElement<int>("id"));
         schema.Elements.Add(new SchemaElement<DateTime>("Timestamp"));
         schema.Elements.Add(new SchemaElement<string>("Message"));
         var ds1 = new DataSet(schema);

         ds1.Add(1, DateTime.Now, "Record1");
         ds1.Add(2, DateTime.Now, "Record2");
         ds1.Add(3, DateTime.Now, "Record3");
         ds1.Add(4, DateTime.Now, "Record4");
         ds1.Add(5, DateTime.Now, "Record5");

         var filePath = $@"C:\temp\AppendTest{DateTime.Now.ToString("yyyyMMddHHmmss")}.parquet";

         //Write part of the file (use actual file stream)
         using (var file = System.IO.File.OpenWrite(filePath))
         {
               ParquetWriter.Write(ds1, file, CompressionMethod.Snappy, null, null, false);
         }

         var ds2 = new DataSet(schema);

         ds2.Add(6, DateTime.Now, "Record6");
         ds2.Add(7, DateTime.Now, "Record7");
         ds2.Add(8, DateTime.Now, "Record8");
         ds2.Add(9, DateTime.Now, "Record9");

         using (var file = System.IO.File.Open(filePath, FileMode.Open, FileAccess.ReadWrite))
         {
            file.Seek(0, SeekOrigin.End);
            ParquetWriter.Write(ds2, file, CompressionMethod.Snappy, null, null, true);
         }

         if (System.IO.File.Exists(filePath)) System.IO.File.Delete(filePath);
      }
````

**Comment by aloneguid** [comment]
Valid point. We didn't have DateTime originally, only DateTimeOffset as it's somewhat suits better, however many developers prefer to work with DateTime so we added it and internally it gets converted into DateTimeOffset. The type information is lost in parquet, so we don't know which CLR type was used originally.

I guess we could make an allowance in IEquatable to treat both types as equal, that might solve the issue.

**Comment by aloneguid** [comment]
I'm going to have a closer look at this tomorrow)

**Comment by grbinho** [comment]
Great. I'm open to doing a PR for this, I was just not sure which direction is preferred.

**Comment by aloneguid** [comment]
@grbinho brilliant, thank you, help is greatly appreciated )
