### ISSUE TITLE
Non-seekable stream fails on GZipStream

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#252]
This is happening due to the fact that `ParquetWriter` calls to `.Position` which is not supported on this stream.

For testing you can wrap `MemoryStream` in `GZipStream`.

**Comment by mukunku** [comment]
Just want to mention that: 
`public Thrift.ColumnChunk AddColumnChunk(CompressionMethod compression, Stream output, SchemaElement schema, int valuesCount)`
also uses the Position property.

**Comment by mukunku** [comment]
So I checked the [MemoryStream](https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/io/memorystream.cs) implementation and, it seems, as long as you don't seek or read from a stream, keeping track of the position is merely keeping track of the bytes written. Please someone correct me if I'm wrong.

So I was able to finally generate a valid Parquet file by implementing my own Position property in the GZipStream class. And successfully read in Apache Spark.

```
private class CustomGZipStream : GZipStream
{
	public CustomGZipStream(Stream stream, CompressionMode compression)
		: base(stream, compression)
	{

	}

	private long position = 0;
	public override long Position
	{
		get
		{
			return position; //This is a temporary fix for the Parquet.Net library.
		}
		set
		{
			throw new NotImplementedException();
		}
	}

	public override void Write(byte[] array, int offset, int count)
	{
		base.Write(array, offset, count);
		position += count;
	}
}
```

**Comment by aloneguid** [comment]
@mukunku latest alpha fixed this issue, therefore you might not need the workaround anymore :) Please feel free to check.

**Comment by mukunku** [comment]
@aloneguid 
I tried the latest release v1.4.0-alpha-164 but this version throws an exception when trying to add null values to a dataset:

  ```
 at System.ThrowHelper.IfNullAndNullsAreIllegalThenThrow[T](Object value, ExceptionArgument argName)
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at Parquet.Data.DataSet.AddRow(Row row)
   at Parquet.Data.DataSet.Add(Object[] values)
   ...
```

I assume you (or someone) added type constraints to the DataSet. But from what I read, DataFrames are supposed to match the SQL practices where non-reference types should be allowed to be null.

[Here is an example article I found on this](https://medium.com/@mrpowers/dealing-with-null-in-spark-cfdbb12f231e)

I'll stick to alpha 161 for now

**Comment by aloneguid** [comment]
@mukunku yes sorry this is one of the changes we've made for dealing with nullable columns as it causes a lot of confusion: https://github.com/elastacloud/parquet-dotnet/blob/master/doc/schema.md#null-values
