### ISSUE TITLE
Parquet file created from HttpResponse stream is corrupt.

### ISSUE THREAD

**Issue by mukunku** [elastacloud/parquet-dotnet#253]
Hi,

I'm running into an issue where if I create the Parquet file using a File Stream I don't experience any issues but if I return the parquet file in a HttpResponse stream, the file ends up being corrupt.

The HttpResponse file is 2Bytes smaller than the FileStream one: [image](https://i.imgur.com/QTOyARF.png)

I'm disposing the ParquetWriter as I should so the stream is definitely getting flushed. And when I compare the two files I can see that there's only a slight difference: [image](https://i.imgur.com/axEo3J2.png)

My first thought is some kind of encoding issue but both files are UNIX ANSI.

Does anyone have any thoughts on why this could be happening?

Thanks.

**Comment by mukunku** [comment]
It seems this is because the Position property is used in the Schema generation. I guess this can be closed as a duplicate of #252

**Comment by aloneguid** [comment]
@mukunku latest alpha now truly supports forward-only streams ;)
