### ISSUE TITLE
Netbox may generate conflicts

### ISSUE THREAD

**Issue by macalbert** [elastacloud/parquet-dotnet#263]
Hi,

First of all thanks for your great job and nice library ;)

Really, do you need to include  **NetBox** library in the project?
I think that this library may generate conflicts, because this overrides as extension the **AsEnumerable()** method of class **Enumerable** in **System.Linq**.

**Comment by aloneguid** [comment]
Thanks @macalbert we're trying ;) Netbox is just a collection of boring repetitive stuff to save on typing which makes some C# functionality faster to develop, there is no real need for it. It shouldn't override any behaviour, only add some extras ;)

**Comment by aloneguid** [comment]
Netbox is removed as a dependency.

**Comment by macalbert** [comment]
nice, great job @aloneguid !

thx :)
