### ISSUE TITLE
Parquet Dataset.Clear does not remove rows added to Dataset

### ISSUE THREAD

**Issue by we7313** [elastacloud/parquet-dotnet#266]
After creating a new dataset (creating the schema for the parquet file).  I would like to add rows and then write them to a file.  Without creating a new dataset object with schema I would like to be able to clear out the rows to add new rows and write again.
The method Dataset.clear is available, but does not clear out the rows.
Is there another way to do this?

**Comment by aloneguid** [comment]
`Clear` is not implemented yet although it's trivial to do - it needs to clear column values (internally data is stored in columns, Row is generated on request).

**Comment by we7313** [comment]
Agreed, its columnar!  Should it not have thrown a not implemented exception?

**Comment by aloneguid** [comment]
@we7313  yes ideally :) seems like a bug! Are you keen to work on it and raise a PR?
