### ISSUE TITLE
Custom metadata in file

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#267]
Add documentation on how to write/read custom metadata to the file. If it's not exposed publicly also needs to be done as well.

**Comment by vasishta79** [comment]
Hi,

Does it support .Net core?  Can someone provide samples for struct and map data type?

Thanks

Ramesh S B

**Comment by aloneguid** [comment]
Yes it does.. Net standard 1.4 and up! Samples are in docs, the link is on front page)

**Comment by AndyCross** [comment]
https://github.com/elastacloud/parquet-dotnet/blob/master/doc/complex.md#maps
