### ISSUE TITLE
Add range method is no longer available

### ISSUE THREAD

**Issue by we7313** [elastacloud/parquet-dotnet#270]
I used to be able to merge multiple datasets with the dataset.addrange(newdataset).

This has no longer been available since version 1.3.
Are you planning on adding this back in?

**Comment by aloneguid** [comment]
@we7313 I'm currently busy with next major version 2.0 which has a lot of cool stuff, probably not until then ;)

**Comment by we7313** [comment]
Cool, I understand.  I do miss this functionality, its how I was merging thousands of parquet files created in my server-less environment.

**Comment by aloneguid** [comment]
@we7313  it should be back in 2.0 and preview should be out this month, for now you can just enumerate rows and add them one by one. This is not fast but that's how it was happening anyway. In 2.0 we'll be able to merge data blazing fast by merging column arrays instead of decomposing into rows.

**Comment by aloneguid** [comment]
done, scheduled for 2.0 release

**Comment by we7313** [comment]
AddRange Method still seems to be unavailable in 2.20 preview.

**Comment by aloneguid** [comment]
@we7313 i'll reopen it for now.

**Comment by aloneguid** [comment]
Closing as not relevant for V3 anymore.
