### ISSUE TITLE
Namespace for EnumerableExtensions causes conflicts

### ISSUE THREAD

**Issue by domdom** [elastacloud/parquet-dotnet#271]
Similar to https://github.com/aloneguid/support/issues/8

**Comment by aloneguid** [comment]
The issue has no description

**Comment by domdom** [comment]
Sorry, I thought the one linked was sufficient since this is essentially the exact same problem.

Essentially, if I were to use this library, its dependency on Netbox introduces extension methods into the System.Collections.Generic namespace that conflict with my own extension methods. There is no way to work around this since those files often depend on other System.Collections.Generic types. 

Of course, it is possible to disambiguate like so:
```
PathToOwnImplementation.ForEach(someList, item => item.DoSomething());
```
But that's a bit painful.

**Comment by aloneguid** [comment]
Hey we have no dependency anymore, if you're upgrading this needs to be removed manually from NuGet

**Comment by domdom** [comment]
Awesome, thanks :)
