### ISSUE TITLE
Add statistics for encoded column metadata

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#280]
To allow efficient query in spark and other clients.

#279 will probably depend on this.

**Comment by amireluk** [comment]
Hi Ivan,
Any plans to implement this feature?

**Comment by TikiBill** [comment]
Thanks for Parquet.NET. It is very useful.

As far as I can tell, the statistics are needed by Drill as well (to query efficiently). It looks like the generated thrift interface code already has an interface for setting the statistics. Have you worked on this at all? If not, I'll poke at it and hopefully generate a pull request in a few weeks.

**Comment by TikiBill** [comment]
I have mostly working code for this. One thing that is currently vexing me is that statistics are not written for strings / binary array -- and also bytes and UInt16. The stats written by drill do have min and max values for string columns, which from what I can tell drill uses.

**Comment by aloneguid** [comment]
Yeah you're right, I have this in progress for a long time and then abandoned for a while. You need to generate stats for all types correctly in order for spark and other engines to benefit from this. There's some compatibility issues between engines as well I didn't have time to figure out. I didn't test it properly either so it's not part of main branch.

**Comment by TikiBill** [comment]
Thanks, good to know. I'll keep working on why the string stats don't show up in the java parquet-tools dump. That being said, I can confirm that Drill will use the stats even if only one column has stats as long as that column is in the query criteria (an Int64 ID column in my case). I put a Boolean in `DataColumn.cs` so calculating stats can be enabled on a per-column basis. Calculating min/max on string comparisons can be kinda slow and I don't really need it in my case.

For good measure, here is the current incarnation of the stats calculation function. Apologies for it not matching the indent of your source, my intent is to clean everything up to match before I submit a pull request.

[ThriftStatsHelper.txt](https://github.com/elastacloud/parquet-dotnet/files/3531984/ThriftStatsHelper.txt)

**Comment by aloneguid** [comment]
Thanks, I'm on holiday at the moment, will come back later this week )

**Comment by KyleGobel** [comment]
Any word on this?  Where can I help?

**Comment by aloneguid** [comment]
@KyleGobel i've realised thrift spec is out of date, just trying to gen to the latest version. I'll share the branch shortly.

**Comment by aloneguid** [comment]
@KyleGobel upgraded thirft specs to latest, working on statistics [in this branch](https://github.com/aloneguid/parquet-dotnet/tree/issues/5-column-stats)

**Comment by TikiBill** [comment]
Since you've upgraded the thrift spec, I can make a pull request against your new branch to populate the statistics. The code I've been using has been working well with Drill for some time. Give me a day or two please.

**Comment by aloneguid** [comment]
@TikiBill thank you, ping me when you're ready.

**Comment by aloneguid** [comment]
Statistics are now supported in v3.5 (see [this branch](https://github.com/aloneguid/parquet-dotnet) for source)
