### ISSUE TITLE
Thrift.Protocol.TProtocolException: 'don't know what type: 13' Exception on read

### ISSUE THREAD

**Issue by GKallarackal** [elastacloud/parquet-dotnet#282]
**Version:** Parquet.Net v2.1.1

#### Expected behavior
Simple Parquet file created and then read back successfully.

#### Actual behavior
An error is encountered on line:
 **dsread = reader.Read()**

The exception is

**Thrift.Protocol.TProtocolException: 'don't know what type: 13'**
### Steps to reproduce the behavior

Run method below.

#### Code snippet reproducing the behavior

```csharp
private void ParquetDemo()
{
    DataSet ds = new DataSet(new DataField<string>("City"), new DataField<Int32>("ID"));
    ds.Add("London", 1);
    ds.Add("Cochin", 2);
    using (Stream fileStream = File.OpenWrite("..\\..\\outputs\\Demo.txt"))
    {
        using (var writer = new ParquetWriter(fileStream))
        {
            writer.Write(ds);
        }
    }

    DataSet dsread;
    using (Stream fs = File.OpenRead("..\\..\\outputs\\Demo.txt"))
    {
        using (var reader = new ParquetReader(fs))
        {
            dsread = reader.Read();
        }
    }
}

```

- [Demo.txt](https://github.com/elastacloud/parquet-dotnet/files/1548397/Demo.txt)

**Comment by aloneguid** [comment]
@GKallarackal exactly same code works for me, can you try absolute file path or just make sure that directory exists?

**Comment by GKallarackal** [comment]
Hi

Thanks for the quick response. The file reading and writing is fine that is
not the problem.

Which version of the .Net Framework are you using? I realise I am using
4.5.2.

Regards

George

**Comment by GKallarackal** [comment]
Problem solved when I changed to 4.6.1.

Regards

George

**Comment by aloneguid** [comment]
@GKallarackal good point, we're running integration tests only under .NET Core 1.1 at the moment. Ideally should be running on several targets.

**Comment by GKallarackal** [comment]
Actually, the use case I have is trying to create files for AWS Athena and
I am struggling to create examples that work in Athena with Double or
Decimal data types.

Should I change to .net core 1.1?

**Comment by aloneguid** [comment]
@GKallarackal framework doesn't matter much, but there is a known issue with Athena and decimal types when it doesn't support decimals according to specs. You should  use `DecimalDataField` and set `forceByteArrayEncoding` to true to be readable by Athena/Impala.

**Comment by GKallarackal** [comment]
Great thanks will give that a go.

George

**Comment by GKallarackal** [comment]
Is there a similar issue with Double?

**Comment by aloneguid** [comment]
No, decimals only ;)

**Comment by GKallarackal** [comment]
I have used code below to create file.

private void CreateFilesTest2()
{
    DataSet ds = new DataSet(new DecimalDataField("ElementID1", 38, 15,
true));
    Random r = new Random;
    ds.Add((decimal)1.23);
    Directory.CreateDirectory("..\\..\\outputs\\Test2\\");
    WriteFile("..\\..\\outputs\\Test2\\SimpleTest.parquet", ds);
    ds.Clear();
}

Then run this on Athena

CREATE EXTERNAL TABLE IF NOT EXISTS default.PeerInsightTest2 (
  `ElementID` DECIMAL (38, 15)
)
STORED AS PARQUET
LOCATION 's3://athenatestgk/Parquet/PeerInsightsTest2/';

followed by

MSCK REPAIR TABLE default.PeerInsightTest2;

But when I

select * from PeerInsightTest2

I get this error:

An error occurred when executing the SQL command:
select * from PeerInsightTest2

HIVE_CANNOT_OPEN_SPLIT: Error opening Hive split
s3://athenatestgk/Parquet/PeerInsightsTest2/SimpleTest.parquet (offset=0,
length=296): can not read class parquet.format.FileMetaData: don't know
what type: 14 [SQL State=FAILED]
1 statement failed.

**Comment by aloneguid** [comment]
I'm not sure to be honest. Well have a look. It may take some time as AWS Athena team is not very responsive)

**Comment by aloneguid** [comment]
@GKallarackal is this still an issue?

**Comment by GKallarackal** [comment]
I was not able to resolve it so yes. I moved forward by storing data as
strings but that is far from ideal.

George

**Comment by aloneguid** [comment]
@GKallarackal sorry I've got a slight problem with AWS as I don't have a test environment for this. Unfortunately AWS doesn't always follow parquet standard, we've seen this many times, therefore these issues. I'll try to arrange something soon.

**Comment by igor-betin** [comment]
I got same problem - it's because AWS streams don't return all data, and ParquetReader always expectes that Stream.Read will return exactly number of bytes requested.
Here https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=netframework-4.7.2 it says:

An implementation is free to return fewer bytes than requested even if the end of the stream has not been reached.
I encountered same error, had to write Stream wrapper that executes Read until count is reached

**Comment by igor-betin** [comment]
More precisely, it's because .Net HTTP treams (AWS being such case) return amount they currently read in their buffer.
I see that everywhere in the code Read is only called on streams once and returned number of bytes actually read is ignored.

**Comment by aloneguid** [comment]
Closing as not an issue. The fact parquet is not streamable format is well known. You have to have file available on the node.
