### ISSUE TITLE
Parquet supporting nullable DataTime, Double etc - for DataLake USQL usage

### ISSUE THREAD

**Issue by mathanrajendran** [elastacloud/parquet-dotnet#287]
**** Parquet.Net v2.1.1

#### Expected behavior

Nullable DateTime Types

#### Actual behavior

Null point reference for [System.DateTime]

### Steps to reproduce the behavior

1. USQL - Create a csv file with Datetime value as null and  read it( Data Lake allows DateTime?)
2. Writing it to Parquet should allow me to write the output as it is from input.

**Comment by aloneguid** [comment]
Hi. Isn't this related to adla project?

**Comment by aloneguid** [comment]
Closing as not related to parquet library.
