### ISSUE TITLE
Error in Parquet reader

### ISSUE THREAD

**Issue by dimpalbhole** [elastacloud/parquet-dotnet#288]
I am getting an error while using parquet reader.
Error is {"fatal error reading column 'SN'"} and message is Unable to read beyond the end of the stream.
I have set TreatByteArrayAsString = true .

My code is:
 var options = new ParquetOptions { TreatByteArrayAsString = true };
DataSet ds = ParquetReader.Read(fs, options, null);

**Comment by aloneguid** [comment]
Hi @dimpalbhole , is there a sample file I can use to reproduce this?

**Comment by aloneguid** [comment]
Closing as there is no information to reproduce.
