### ISSUE TITLE
Nullable MapField and StructField

### ISSUE THREAD

**Issue by edwinloubser** [elastacloud/parquet-dotnet#290]
Hey,

From what I can tell null values for the MapField and StructField are not allowed.  Is there a way to work around this?  

Example of schema I have:
var schema = new Field[]
				{
					new DataField<ushort>("Version"),
					new DataField<long>("EventId"),
					new DataField<long>("EventTypeId"),
					new ListField("EntityIdentifiers", new StructField("item", new DataField[]
					{
						new DataField("EntityId", DataType.Int64, false),
						new DataField("EntityTypeOrRole", DataType.String,true),
						new DataField("DomainName", DataType.String,true),
						new DataField("LegacyId", DataType.Int32, true)
					})),
					new DataField("StartDateTime", DataType.DateTimeOffset, true),
					new DataField("EndDateTime", DataType.DateTimeOffset, true),
					new MapField("OtherData", new DataField<string>("Key"), new DataField<string>("Value")),
					new DataField<bool>("IsActive"),
					new DataField<bool>("HasMedia"),

					new StructField("StartPosition", PositionTranslator.GetLayout()),
					new StructField("EndPosition", PositionTranslator.GetLayout())
				};

OtherData, StartPosition or EndPosition could be all be null. If managed to work around the issue for MapField by passing in an empty instance of an dictionary.  But obviously this is a bit much for Start & End position as it is a complex object as indicated below.  Any help would be much appreciated.

public static Field[] PositionTranslator.GetLayout()
		{
			return new Field[]
				{
					new DataField<ushort>("Version"),
					new DataField<long>("PositionId"),
					new ListField("EntityIdentifiers", new StructField("item", new DataField[]
					{
						new DataField("EntityId", DataType.Int64, false),
						new DataField("EntityTypeOrRole", DataType.String,true),
						new DataField("DomainName", DataType.String,true),
						new DataField("LegacyId", DataType.Int32, true)
					})),

					new DataField<DateTime>("Timestamp"),
					new DataField<double>("Latitude"),
					new DataField<double>("Longitude"),
					new DataField<float?>("SpeedKilometresPerHour"),
					new DataField<int?>("AltitudeMetres"),
					new DataField<ushort?>("Heading"),
					new DataField<byte?>("NumberOfSatellites"),
					new DataField<byte?>("Hdop"),
					new DataField<byte?>("Vdop"),
					new DataField<byte?>("Pdop"),
					new DataField("AgeOfReadingSeconds", DataType.Int64, true),
					new DataField<bool?>("IgnitionOn"),
					new DataField<float?>("OdometerKilometres"),
					new DataField<string>("FormattedAddress"),
					new DataField<bool>("IsSignificant"),
					new DataField<bool>("IsAvl"),
					new DataField<ushort?>("DistanceSinceReadingKilometres"),
					new DataField<byte?>("Source"),

					new MapField("AddressRecords", new DataField<string>("Key"), new DataField<string>("Value")),
					new MapField("AddressAttributes", new DataField<string>("Key"), new DataField<string>("Value")),
					new MapField("CustomDataRecords", new DataField<string>("Key"), new DataField<string>("Value")),
					new MapField("OtherData", new DataField<string>("Key"), new DataField<string>("Value"))
				};
		}

**Comment by aloneguid** [comment]
You're right, it's not supported yet. It shouldn't be too hard to implement though.

**Comment by edwinloubser** [comment]
Thanks for the feedback. I've worked around it for now, but would be great if this could be implemented as I think it is a common scenario.

**Comment by aloneguid** [comment]
@edwinloubser i'll be looking at this over next few days.

**Comment by aloneguid** [comment]
@edwinloubser i think it's fixed, you can try by referencing `2.2.0-preview-268` from this NuGet feed https://ci.appveyor.com/nuget/parquet-dotnet. If it works for you i'll release it ;)

**Comment by edwinloubser** [comment]
@aloneguid Thanks! Will try it out on Monday and let you know.

**Comment by edwinloubser** [comment]
@aloneguid Tried out the Preview and I'm still getting an exception.  The exception occurs when trying to add the Row to a DataSet.   Here is the StackTrace:

   at System.ThrowHelper.IfNullAndNullsAreIllegalThenThrow[T](Object value, ExceptionArgument argName)
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at Parquet.Data.RowAppender.Append(Dictionary`2 columns, IReadOnlyList`1 schema, Row row)
   at Parquet.Data.RowAppender.Append(Dictionary`2 columns, IReadOnlyList`1 schema, Row row)
   at Parquet.Data.DataSet.AddRow(Row row)
   at Parquet.Data.DataSet.Add(Row item)
   at MiX.ResourceData.DataAccess.Parquet.EventTranslator.ConvertTo(IList`1 entities) in C:\Projects\MiX.ResourceData\MiX.ResourceData.DataAccess.Parquet\EventTranslator.cs:line 78

**Comment by aloneguid** [comment]
did you use exactly `2.2.0-preview-268`?

**Comment by edwinloubser** [comment]
I did use exactly that version.

**Comment by aloneguid** [comment]
@edwinloubser can you provide shortest possible code to reproduce this please?
