### ISSUE TITLE
Support controlling row group byte size when writing

### ISSUE THREAD

**Issue by renyuan1010** [elastacloud/parquet-dotnet#293]
Current implementation of RowGroupSize in WriterOptions is the number of row. Very useful to support controlling the actual byte size of a row group.

**Comment by aloneguid** [comment]
This is slightly complicated due to the fact that we don't know exactly what the data size will be after logical and physical compression. Although next major version will have much more control over this.

**Comment by aloneguid** [comment]
@renyuan1010 latest V3 supports controlling row group sizes. Feel free to reopen if it's not suitable.
