### ISSUE TITLE
Support .NET 4.5 and up

### ISSUE THREAD

**Issue by dwaijam** [elastacloud/parquet-dotnet#294]
#### Expected behaviour
Parquet.Net currently supports .NET 4.5 and up. This will allow it to be used by projects targeting.Net 4.5

#### Actual behavior
Parquet.Net currently supports .NET 4.5.1 and up. However, it can be changed to support .Net 4.5 and up with some minor refactorings without any loss of functionality.

### Steps to reproduce the behaviour

Add Parquet.Net dependency to  .Net project targeting 4.5 and build fails

### Contribute

 I am happy to contribute to this repository by fixing this issue and raising a Pull Request

**Comment by aloneguid** [comment]
@dwaijam I'm not sure if any api is missing from .net 4.5 to be honest. I'm happy for you to take this.

**Comment by dwaijam** [comment]
Closing this issue as changes have been merged
