### ISSUE TITLE
Upgrade visibility of certain classes, enums, methods and properties for a custom parquet reader implementation

### ISSUE THREAD

**Issue by dwaijam** [elastacloud/parquet-dotnet#296]
#### Expected behavior

Certain classes, enums, methods and properties are required to be used if a custom Parquet Reader class needs to be implemented. Some of them are as follows
Thrift/FileMetaData.cs
Thrift/ColumnChunk.cs
Thrift/RowGroup.cs
Parquet/ParquetActor.cs
Parquet/File/ThriftFooter.cs
Parquet/Data/Schema/Field.cs
Parquet/Data/Schema/MapField.cs
Parquet/File/Values/Primitives/Interval.cs
Currently, these are marked as default or internal and need to be made public for them to be accessed outside of the dll.

#### Actual behavior

A custom parquet reader cannot be implemented as the required classes are not public.

#### Contribute
- [x] I am happy to contribute to this repository by fixing this issue and raising a Pull Request

**Comment by dwaijam** [comment]
Added PR for the change I am suggesting 
https://github.com/elastacloud/parquet-dotnet/pull/297

**Comment by mandyshieh** [comment]
PR #300 for limited changes.

**Comment by aloneguid** [comment]
released to nuget as v2.1.3
