### ISSUE TITLE
Implement Delta Encoding (DELTA_BINARY_PACKED = 5)

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#3]
Encoding reference - https://github.com/apache/parquet-format/blob/master/Encodings.md#delta-encoding-delta_binary_packed--5

**Comment by aloneguid** [comment]
Hi @sandy-may are you still keen to work on this one?

**Comment by sandy-may** [comment]
@aloneguid I'll unassigned for now so not blocking, but would be good to pair on if you haven't done when I next down

**Comment by aloneguid** [comment]
@sandy-may cool, let me know when you're ready, i'll keep it reserved ;)

**Comment by aloneguid** [comment]
Closing as this encoding is never used.
