### ISSUE TITLE
Can't load parquet file generated with fastparquet

### ISSUE THREAD

**Issue by 0x0L** [elastacloud/parquet-dotnet#304]
**Version:** Parquet.Net git master
**Runtime Version:** .Net Framework v45
**OS:** Windows

First of all, thanks for this project.

I generated some sparse data

```python
s = pd.DataFrame({'test': np.random.randn(1_000_000)})
s[::2] = np.nan
s.to_parquet('test.parquet')
```

Parquet.Net can't read back that file, the process gets stuck.

**Comment by aloneguid** [comment]
Can you attach a sample generated file here?

**Comment by 0x0L** [comment]
see https://github.com/0x0L/temp

**Comment by 0x0L** [comment]
Actually it's a performance issue. The file was read in the end but it took 1min for a million row.

**Comment by 0x0L** [comment]
Financial data, lots of NaNs.

I just finished writing a fix for this:

Moved `InsertDefinitions` to `IDataTypeHandler` and changed signature to

```csharp
IList InsertDefinitions(
            IList values, int maxDefinitionLevel, List<int> definitions,
            out List<bool> hasValueFlags);
```

`BasicDataTypeHandler` gets the normal `InsertDefinitions` implem.

`BasicPrimitiveDataTypeHandler` gets an optimized version using arrays an preallocating.

and finally, null can be encoded as nan for doubles, `DoubleDataTypeHandler` also gets it's specialized version for both `CreateEmptyList` (type is never double?) and `InsertDefinitions`

Seems to work fine. I haven't benchmarked it extensively nor tested too much

**Comment by aloneguid** [comment]
@0x0L sounds good, please raise a PR ;)
Do you need to generate schema dynamically or is it pre-defined? I'm working on low level serialiser which can turn any data structure into parquet stream and back, that's the reason i'm asking ;)

**Comment by 0x0L** [comment]
Interesting! That's somehow the problem I'm trying to solve too but for a much narrower scope (only plain pandas-like dataframes and I'm currently only interested in reading it from C# side). Ideally I want to match fastparquet.to_pandas performances.

I'm not really happy with this yet, it's only a quick a dirty patch and it's still unable too read my big parquet files. It's available at https://github.com/0x0L/parquet-dotnet though (I took the liberty of moving a few things ;) around)

IMO all the columns should be entirely allocated and use arrays instead of lists. However, I might be biased due to my use cases

**Comment by 0x0L** [comment]
@aloneguid 

Hi 
I just noticed the huge perf improvements coming from your new implementation of DataColumns. 
For `double` do you think it's necessary to keep double? instead of using double.nan ?

**Comment by aloneguid** [comment]
@0x0L thank you, we worked hard on this, however still not happy with performance, there are plenty of ideas how to push it to the limits, unfortunately free time is limited ;) Array pooling in .NET seems to be an answer to GC pressure, however a few places in code need to be changed to work with pooled arrays instead of pre-allocated ones.

I'm not quite sure regarding null and NaN, it depends. NaN represents a meaningful value for doubles, whereas null is an absence of a value. It's also hard to tell whether performance wise using NaN is better or not as comparing NaNs incurs an overhead of a method call. It's interesting though, are NaNs portable between languages i.e. is Java NaN same as C# NaN?

**Comment by 0x0L** [comment]
double?[] are way slower than double[] because of all the boxing/unboxing (with netcore, it's roughly 5 times slower). NaN are part of IEEE 754 so AFAIK there's virtually no overhead and they are portable

**Comment by aloneguid** [comment]
We can prototype it and see if it works?

**Comment by 0x0L** [comment]
Sound good. I can give it a try if you want.
Do you have any large reference for performance testing ?

**Comment by 0x0L** [comment]
Just reimplemented 

```csharp
      private double[] UnpackDefinitions(double[] src, int[] definitionLevels, int maxDefinitionLevel)
      {
         double[] result = (double[])GetArray(definitionLevels.Length, false, true);

         int isrc = 0;
         for (int i = 0; i < definitionLevels.Length; i++)
         {
            int level = definitionLevels[i];

            if (level == maxDefinitionLevel)
            {
               result[i] = src[isrc++];
            }
            else
            {
               result[i] = double.NaN;
            }
         }

         return result;
      }
```

I generated a file  11000 x 1000 with a single continuous band of nans in each column. Reading performance is only slightly better ~10%. We may gain a bit more by preinitializing the entire array to nan using some low level sys function. 

In the end it looks more like a matter of convenience than pure performance

**Comment by aloneguid** [comment]
Might be related to #334

**Comment by aloneguid** [comment]
@0x0L it looks like the file generated is not a parquet file. I think what happens here:

```python
from fastparquet import ParquetFile
from fastparquet import write
import pandas as pd
import numpy as np

s = pd.DataFrame({'test': np.random.randn(1_000_000)})
s[::2] = np.nan
s.to_parquet('test.parquet')
```
is pandas trying to use SNAPPY codec which is not available by default and generates garbage. However, if you choose compression explicitly and set it to gzip or uncompressed the generated file is perfectly readable i.e. both lines work:

```python
s.to_parquet('test.parquet', compression='uncompressed')
s.to_parquet('test.parquet', compression='gzip')
```
