### ISSUE TITLE
Bug in BooleanDataTypeHandler

### ISSUE THREAD

**Issue by yifatso** [elastacloud/parquet-dotnet#305]
#### Actual behavior

Boolean types are not serialized correctly (see suggested code change in BooleanDataTypeHandler). 

### Steps to reproduce the behavior

Write and read a type with boolean values. 

#### Suggested bug fix 
Write method in BooleanDataTypeHandler.Write method only advances the 'n' variable cursor on 'true' values. Suggested fix - instead of: 

            if (flag)
            {
               b |= (byte)(1 << n++);
            }
             if (n == 8)
            {  .... 

Should be: 

           if (flag)
            {
               b |= (byte)(1 << n);
            }
            n++;
            if (n == 8)
            {  .... 

Since this is such a small change, I'd appreciate it if one of the maintainers could fix it and save me the pull request procedure. Otherwise, please let me know and I'll submit a PR. 
Thank you for this project!  
Yifat.

**Comment by aloneguid** [comment]
@yifatso released as 2.1.4, thank you!
