### ISSUE TITLE
ParquetWriter.WriteFile ignores the append parameter

### ISSUE THREAD

**Issue by mlmanfredi** [elastacloud/parquet-dotnet#311]
**Version:** Parquet.Net v2.1.4
**Runtime Version:** .Net Framework v4.7.1
**OS:** Windows 7

#### Expected behavior

When the append parameter is true, the data being written should be added to the existing data in the file.

#### Actual behavior

Regardless of the append parameter value, the current file data is overwritten. The WriteFile function code does nothing with the append parameter.

### Steps to reproduce the behavior

1. Create new file using WriteFile
2. Append to the same file using WriteFile
3. Read the file and check results.

#### Code snippet reproducing the behavior

This is your unit test for appending with the Write function modified to use WriteFile.

```csharp
	   public void Append_to_disk_file_reads_all_dataset()
	   {
	      var file = Path.GetTempFileName();

	      try
	      {
	         var ds1 = new Parquet.Data.DataSet(new DataField<int>("id"));
	         ds1.Add(1);
	         ds1.Add(2);
	         Parquet.ParquetWriter.WriteFile(ds1, file);

	         //append to file
	         var ds2 = new Parquet.Data.DataSet(new DataField<int>("id"));
	         ds2.Add(3);
	         ds2.Add(4);
	         ParquetWriter.WriteFile(ds2, file, CompressionMethod.Gzip, null, null, true);

	         Parquet.Data.DataSet dsAll = ParquetReader.ReadFile(file);

	         Assert.Equal(4, dsAll.RowCount);
	         Assert.Equal(new[] { 1, 2, 3, 4 }, dsAll.GetColumn((DataField)ds1.Schema[0]));
	      }
	      finally
	      {
	         System.IO.File.Delete(file);
	      }
	   }
```
#### Code snippet suggested fix

```csharp
      public static void WriteFile(DataSet dataSet, string fileName, CompressionMethod compression = CompressionMethod.Gzip, ParquetOptions formatOptions = null, WriterOptions writerOptions = null, bool append = false)
      {
         using (Stream fs = append ? System.IO.File.Open(fileName, FileMode.Open) : System.IO.File.Create(fileName))
         {
            using (var writer = new ParquetWriter(fs, formatOptions, writerOptions))
            {
               writer.Write(dataSet, compression, append);
            }
         }
      }
```

- [ ] I'm attaching a sample .parquet file containing the problem.
- [ ] I am happy to contribute to this repository by fixing this issue and raising a Pull Request (see [contribution guide](CONTRIBUTING.md))

**Comment by aloneguid** [comment]
This is fixed in V3, please feel free to reopen if it still doesn't work.
