### ISSUE TITLE
library does not support timstamp logical type

### ISSUE THREAD

**Issue by dashtimehran** [elastacloud/parquet-dotnet#312]
This library does not support timestamp logical type that is encoded to physical type of  int64 .
Is it any plan to support it in a few days.
thank you in advance.

**Comment by aloneguid** [comment]
@dashtimehran just to be clear which one are you looking for? https://github.com/apache/parquet-format/blob/master/LogicalTypes.md

It's not in the plans to extend types in the nearest weeks as we're busy with V3, however I'll be happy to approve a PR if you're comfortable contributing to the library?

**Comment by dashtimehran** [comment]
I 'm busy these days. If I've got some time I will let you know.
