### ISSUE TITLE
Path Separator issue

### ISSUE THREAD

**Issue by Sudhir87** [elastacloud/parquet-dotnet#314]
**Version:** Parquet.Net v...
**OS:** Windows

#### Expected behavior

The file should get read in the viewer.

#### Actual behavior

I would like to understand what are the special characters used for path separator as I am getting the below error? Attaching the column list for your reference. 
![image](https://user-images.githubusercontent.com/41491841/43034807-063eec38-8d01-11e8-887b-54e3c9f8669f.png)

### Steps to reproduce the behavior

Attaching the column list for your reference. 
#### Code snippet reproducing the behavior

[Lead_Test1.zip](https://github.com/elastacloud/parquet-dotnet/files/2216083/Lead_Test1.zip)

**Comment by aloneguid** [comment]
Hi @Sudhir87. Only dot (.) is not allowed in field name, as apache parquet format uses it as field path separator for complex structures.
