### ISSUE TITLE
Reading parquet files with multiple pages doesn't read beyond 1st page

### ISSUE THREAD

**Issue by Confusedfish** [elastacloud/parquet-dotnet#318]
**Version:** Parquet.Net v3.0.2

**Runtime Version:** .Net Core v 2.1.2

**OS:** Windows

#### Expected behavior

Reading a parquet file with a large number of rows should populate all pages of data. The file in question uses a dictionary on the column.

#### Actual behavior

When reading the data back from the ParquetReader, any records beyond the first page boundary all use the first record, i.e. dictionary entry 0

### Steps to reproduce the behavior

1. Create a large parquet file (page file in my example is 524288 with close to 1M rows)
2. Read the file using ParquetReader, iterating the row groups and retrieving the column data
3. Compare the data with the original, records after the 1st page will all match the 1st record

#### Code snippet reproducing the behavior

```csharp
      [Fact]
      public void Reads_multi_page_file()
      {
         using (var reader = new ParquetReader(OpenTestFile("multi.page.parquet"), leaveStreamOpen: false))
         {
            DataColumn[] data = reader.ReadEntireRowGroup();
            Assert.Equal(927861, data[0].Data.Length);

            int[] firstColumn = (int[])data[0].Data;
            Assert.Equal(30763, firstColumn[524286]);
            Assert.Equal(30766, firstColumn[524287]);

            //At row 524288 the data is split into another page
            //The column makes use of a dictionary to reduce the number of values and the default dictionary index value is zero (i.e. the first record value)
            Assert.NotEqual(firstColumn[0], firstColumn[524288]);

            //The vlaue should be 30768
            Assert.Equal(30768, firstColumn[524288]);
         }
      }
```

- [X] I'm attaching a sample .parquet file containing the problem.
- [X] I am happy to contribute to this repository by fixing this issue and raising a Pull Request (see [contribution guide](CONTRIBUTING.md))

**Comment by aloneguid** [comment]
thanks again, released as v3.0.3 on nuget

**Comment by Confusedfish** [comment]
Hi @aloneguid did you see my comment relating to a possible duplicate of this issue? (I am now not sure where my comment went) I am not sure if it is necessary to also make the [following change](https://github.com/Confusedfish/parquet-dotnet/commit/c17f2fbd6a8c9a7055e6c19394f4350f9f5ecd37), what do you think?

**Comment by aloneguid** [comment]
@Confusedfish yes you're right! Would be brilliant to get some tests ready for reading multiple row groups. I think we might be missing something else.

**Comment by aloneguid** [comment]
@Confusedfish no problem, thank you! ;) I've added tests that generate multiple row groups dynamically, after your changes. They all seem to pass therefore I didn't release a new version.
