### ISSUE TITLE
A nullable field should support all-non-nullable values

### ISSUE THREAD

**Issue by dzhang-quest** [elastacloud/parquet-dotnet#321]
**Version:** Parquet.Net v3.0.4

**Runtime Version:** .Net Framework v4.6.1

**OS:** Windows 10 Version 1709

#### Expected behavior
a nullable field, `DataField<long?>("id")`, should support all-non-nullable values, `long?[] { 1, 2, 3 }`. 

#### Actual behavior
An exception was thrown:
System.InvalidCastException : Unable to cast object of type 'System.Nullable`1[System.Int64][]' to type 'System.Int64[]'.

StackTrace:	
at Parquet.Data.BasicDataTypeHandler'1.Write(SchemaElement tse, BinaryWriter writer, IList values)
   at Parquet.File.DataColumnWriter.WriteColumn(DataColumn column, SchemaElement tse, IDataTypeHandler dataTypeHandler, Int32 maxRepetitionLevel, Int32 maxDefinitionLevel)
   at Parquet.File.DataColumnWriter.Write(List'1 path, DataColumn column, IDataTypeHandler dataTypeHandler)
   at Parquet.ParquetRowGroupWriter.WriteColumn(DataColumn column)
   at Parquet.Test.ParquetWriterTest.WriteNullableArray() in C:\Users\dzhang\repos\parquet-dotnet\src\Parquet.Test\ParquetWriterTest.cs:line 21

### Steps to reproduce the behavior

1. Create a nullable data field of primary type
2. Write a nullable array without null values using ParquetRowGroupWriter

#### Code snippet reproducing the behavior

```c#
var id = new DataField<long?>("id");
var ms = new MemoryStream();

using (var writer = new ParquetWriter(new Schema(id), ms))
{
   using (ParquetRowGroupWriter rg = writer.CreateRowGroup(3))
   {
      rg.WriteColumn(new DataColumn(id, new long?[] { 1, 2, 3 }));

   }
}
```

- [ ] I'm attaching a sample .parquet file containing the problem.
- [x] I am happy to contribute to this repository by fixing this issue and raising a Pull Request (see [contribution guide](CONTRIBUTING.md))

**Comment by dzhang-quest** [comment]
If there is no null values in a nullable array, the following code will return the original array.
https://github.com/elastacloud/parquet-dotnet/blob/55f0cb7a0137bde433eb1a05bab35d63da7208de/src/Parquet/Data/DataColumn.cs#L106

When the array is passed to here
https://github.com/elastacloud/parquet-dotnet/blob/55f0cb7a0137bde433eb1a05bab35d63da7208de/src/Parquet/Data/BasicDataTypeHandler.cs#L74

the following exception will be thrown.
System.InvalidCastException : Unable to cast object of type 'System.Nullable`1[System.Int64][]' to type 'System.Int64[]'

**Comment by dzhang-quest** [comment]
@aloneguid I will do it soon.

**Comment by dzhang-quest** [comment]
@aloneguid Could you review #325 ?

**Comment by aloneguid** [comment]
@dzhang-quest all good, thank you. Pushing new version to nuget now.
