### ISSUE TITLE
UUID is not Encoded [Feature Request]

### ISSUE THREAD

**Issue by slogen** [elastacloud/parquet-dotnet#324]
**Version:** Parquet.Net v2.1

**Runtime Version:** NA

**OS:** Windows/Linux NA

#### Expected behavior

I expected .NET Guid fields to be serialized as specified in https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift (16 bytes, big-endian)

#### Actual behavior

Guid fields are not serialized

### Steps to reproduce the behavior

1. Add a Guid and validation to `Serialise_deserialise_all_types()` in `ParquetConvertTest.cs` (as done in https://github.com/slogen/parquet-dotnet/commit/2784a2dfb3364bdfcf1c5acab7a3c3781945c118)
2. Run `Serialise_deserialise_all_types()`

#### Code snippet reproducing the behavior

https://github.com/slogen/parquet-dotnet/commit/2784a2dfb3364bdfcf1c5acab7a3c3781945c118

- [ ] I'm attaching a sample .parquet file containing the problem.
- [x] I am happy to contribute to this repository by fixing this issue and raising a Pull Request (see [contribution guide](CONTRIBUTING.md))

**Comment by slogen** [comment]
I have attempted an initial implementation at https://github.com/slogen/parquet-dotnet/commit/757aa91aaee672aac2ec55b2348f132edbf70801. 

It passes the tests (recovering the Guids). I will probably need a little support to make sure it follows practices and covers all corners

**Comment by aloneguid** [comment]
Hey @slogen just looked at your code and left some comments inline. It generally looks good, happy to help as much as I can to push this to PR ;)
