### ISSUE TITLE
V2/V3 questions

### ISSUE THREAD

**Issue by jaley** [elastacloud/parquet-dotnet#329]
Hi,

First up, thanks for your work on Parquet.NET. I'm working in the SwiftKey team at Microsoft in London and we use Parquet files very heavily here. I need to integrate with some other .NET-based systems so your work on this library looks super helpful.

I have questions about working with V2 and V3, which I'd ideally send to a mailing list for discussion, but I couldn't see one linked anywhere. Let me know if there's a more appropriate forum than GitHub issues for this.

I'm not sure whether my project should be based on V2 or V3 APIs at this point, as they seem radically different. I'd normally prefer to go with the release candidate for the new APIs knowing that's the right long term investment to be making and help harden that new version by contributing fixes as we find issues. In this case, the API seems far lower-level and I can't help but wonder if higher-level wrappers are planned?

As far as I can tell, the V3 APIs require that the user has quite extensive knowledge of Parquet internals, including knowing how to set repetition and definition levels for nested and collection data types themselves. It feels like that's pretty easy for users to get wrong, and derived from the values and schema being passed in, so could be handled by the library? The V2 API was much easier to use, from my point of view.

Can you explain the thinking behind the V3 API design? I'd like to understand what's preferable about this lower level API, and if/why we should be using that over the simpler V2 approach?

Thanks!

James

**Comment by AndyCross** [comment]
Hi James

V3 is a more true representation of the parquet specification in code. There are some exceptionally helpful helpers in there to abstract some of that (look at ParquetConvert) but we aim to give low level control in line with the parquet format specification. 

I recommend using V3 - we use it everywhere internally at Elastacloud now, having moved away from V2. 

Elastacloud provides commercial support for Parquet.Net, therefore please write to parquetsupport@elastacloud.com to dive a bit deeper into our thinking.

We're also based in London, so maybe we could arrange a tea ;-) 

Andy
