### ISSUE TITLE
Failure to read columns if data page is larger than it should be (supposably padded by Spark)

### ISSUE THREAD

**Issue by DMMDTOM** [elastacloud/parquet-dotnet#330]
Error reading double column.
I have attached the repro parquet.  I have a single column parquet which is erroring out when I try to read it (with the latest).

It has 1 row group, the first three pages are Plain_Dictionary and read right, the final page switches over to PLAIN THRIFT and fails.  If I switch the final page over to Plain-Dictionary (via breakpoints and moving executing code path) , it will finish.

The data consists of a lot of zeros, and it a fairly sparse column.

- [ x] I'm attaching a sample .parquet file containing the problem.
- [ ] I am happy to contribute to this repository by fixing this issue and raising a Pull Request (see [contribution guide](CONTRIBUTING.md)
[repro.parquet.zip](https://github.com/elastacloud/parquet-dotnet/files/2348939/repro.parquet.zip)

**Comment by aloneguid** [comment]
I *think* I have a fix for this.

**Comment by aloneguid** [comment]
This will be included in the next minor bugfix release.

**Comment by DMMDTOM** [comment]
Awesome!  Thank you.
