### ISSUE TITLE
Streams that don't return all bytes requested fail on ParquetReader

### ISSUE THREAD

**Issue by igor-betin** [elastacloud/parquet-dotnet#331]
It's an overall comment on cases like issue 282:

I see that everywhere in the code Read is only called on streams once and returned number of bytes actually read is ignored. 
Maybe in Java a stream is obligated to return all bytes request, but in .NET (see https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=netframework-4.7.2) it's like this:
"An implementation is free to return fewer bytes than requested even if the end of the stream has not been reached."

.NET Core 2.0, on both Linux and Window 10 machines, ver 2.1.3 - it's not really relevant here

**Comment by igor-betin** [comment]
A possible solution is to use Stream wrappers like this one:


        public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
        {
            if (count > buffer.Length - offset)
                count = buffer.Length - offset;
            int totalRead = 0;
            while (true)
            {
                var read = await _stream.ReadAsync(buffer, offset + totalRead, count - totalRead, cancellationToken);
                totalRead += read;
                if (read == 0 || totalRead == count)
                    break;
            }
            return totalRead;
        }


where _stream is the wrapped input stream

**Comment by aloneguid** [comment]
Good find, thank you! Do you mind raising a PR for this?

**Comment by igor-betin** [comment]
Yep, will do
