### ISSUE TITLE
ReaderOptions.Offset doesn't reduce number of bytes read by ParquetReader

### ISSUE THREAD

**Issue by igor-betin** [elastacloud/parquet-dotnet#332]
**Version:** . 2.1.3 
NET Core 2.0, on both Linux and Window 10 machines

#### Expected behavior

We have very large files in Data Lake. Downloading them is not an option, so we provide Stream that supports seeking and download only portions requested by the reader.
We expect for {Offset=5000, Rows=1000} ParquetReader to skip the number of bytes the first 5000 rows use using Seek, and then read bytes continously

#### Actual behavior

For {Offset=5000, Rows=1000} ParquetReader just reads from byte 0 to the end of 6000th row

### Steps to reproduce the behavior

Use any stream with logging as input, try to skip any amount of rows using ParquetReader 

I'd be happy to help but I'm not sure the protocol supports predicting of number of bytes rows use. Maybe you could guess-seek ahead couple of times, or after first read store a map of entries somewhere

**Comment by igor-betin** [comment]
Can you please tell if it's possible at all or shouldn't we even try? If fixing this is possible we will fix and contribute

**Comment by aloneguid** [comment]
Hi @igor-betin we're not looking at v2 support anymore, all the development is currently happening for v3 only. You might find that v3 already solves the issue, if not please reopen ;)
