### ISSUE TITLE
Issue reading Parquet via Impala

### ISSUE THREAD

**Issue by AidasTruskauskas** [elastacloud/parquet-dotnet#334]
**Version:** Parquet.Net version 3.05

**Runtime Version:** .Net Framework v4.6.1

**OS:** Windows 10

#### Generated Parquet file is not working with impala;
we should be able to query the file using Impala;

#### Actual behavior:
SELECT * FROM parquet in impala is not returning any records:

### Steps to reproduce the behavior

1) Parquet file was generated using parquet.net library (please find attached the file): 
    https://github.com/elastacloud/parquet-dotnet#getting-started (wirting files example)

2) parquet file placed in hdfs; (put command)

3) Create external table:

CREATE EXTERNAL TABLE nifi_tbl_test_parquet(
  id INT,
  city STRING)
STORED AS PARQUET
LOCATION  '/user/hue/nifi/nifi_tbl_test_parquet/';

4) Refresh:
REFRESH mytestdb.nifi_tbl_test_parquet;
REFRESH MYTESTDB.nifi_tbl_test_parquet;

5) Run Select statement: 

SELECT *
FROM nifi_tbl_test_parquet;

### Notes
We raised this issue with Cloudera, and this is the response we got:

"The engineering team was able to find that  it seems that this .NET parquet library does not write the file metadata correctly. 

When we tried to query the problematic table via Impala through Hue, the following log message was observed:
File 'hdfs://cdh-centos.cloudera.com:8020/user/systest/test.parquet' is corrupt: metadata indicates a zero row count but there is at least one non-empty row group.

So it seems that the library does not write the num_rows metadata field in RowGroup or FileMetadata field properly, which remains unnoticed by Hive but causes problems in Impala."

[Parquet_Issue.pdf](https://github.com/elastacloud/parquet-dotnet/files/2357660/Parquet_Issue.pdf)
[test.zip](https://github.com/elastacloud/parquet-dotnet/files/2357663/test.zip)

- [* ] I'm attaching a sample .parquet file containing the problem.
- [ ] I am happy to contribute to this repository by fixing this issue and raising a Pull Request (see [contribution guide](CONTRIBUTING.md))

**Comment by aloneguid** [comment]
Confirmed this is an issue. Wasn't surfaced before as we mainly test with Java/Python libraries. Thanks @AidasTruskauskas

**Comment by aloneguid** [comment]
@AidasTruskauskas the fix will be included in the upcoming 3.1 release. We are removing parameter from `writer.CreateRowGroup(rowCount)` completely and the count will be calculated internally for all parts.
