### ISSUE TITLE
DateTimeFormat is not handled properly

### ISSUE THREAD

**Issue by droppedcode** [elastacloud/parquet-dotnet#337]
**Version:** Parquet.Net v3.0.5

**Runtime Version:** .Net Framework v461

**OS:** Windows v10

#### Expected behavior

Reading a column with Thrift.ConvertedType.TIMESTAMP_MILLIS will use milliseconds and not seconds.

#### Actual behavior

Currently in OtherExtensions.cs the following methods use (Add/Total)Seconds and not Milliseconds in case of TIMESTAMP_MILLIS 
      public static DateTime FromUnixTime(this long unixTime)
      {
         return UnixEpoch.AddSeconds(unixTime);
      }

      public static long ToUnixTime(this DateTimeOffset date)
      {
         return Convert.ToInt64((date - UnixEpoch).TotalSeconds);
      }

From the description of parquet https://github.com/apache/parquet-format/blob/master/LogicalTypes.md
TIMESTAMP with precision MILLIS is used for millisecond precision. It must annotate an int64 that stores the number of milliseconds from the Unix epoch, 00:00:00.000 on 1 January 1970, UTC.

### Steps to reproduce the behavior

Read a parquet file *not* created with parquet.net

#### Code snippet reproducing the behavior

I have used the how to read a file from the main page.

- [x
[telemetry_debug.zip](https://github.com/elastacloud/parquet-dotnet/files/2404504/telemetry_debug.zip)
] I'm attaching a sample .parquet file containing the problem.
- [ ] I am happy to contribute to this repository by fixing this issue and raising a Pull Request (see [contribution guide](CONTRIBUTING.md))

**Comment by moggy001** [comment]
I fixed this issue in the previous version of the library. I'm surprised that my fix was not propagated into this version of the library.

**Comment by aloneguid** [comment]
released in v3.2.6
