### ISSUE TITLE
Adding extras to Parquet file

### ISSUE THREAD

**Issue by SatyamG329** [elastacloud/parquet-dotnet#350]
**Version:** Parquet.Net 3.1.4

**Runtime Version:** .Net Framework v4.7 .Net Core 2.1

**OS:** Windows

#### Expected behavior

new feature request
- to have keyValue metadata present in ParquetFile (when writing new parquet file) or capability to add metadata to parquet file 

#### Actual behavior
- no metadata is present in newly created parquet file

Please describe how **Parquet.Net** is behaving.

### Steps to reproduce the behavior

Create a new parquet file with any schema

#### Code snippet reproducing the behavior

use parquet-tool to view meta data of created Parquet file (jar available online)
command -> java -jar parquet-tool.jar meta *.snappy.parquet

```csharp
//here
```

- [Yes
[test-k.snappy.zip](https://github.com/elastacloud/parquet-dotnet/files/2488672/test-k.snappy.zip)

] I'm attaching a sample .parquet file containing the problem.
- [ ] I am happy to contribute to this repository by fixing this issue and raising a Pull Request (see [contribution guide](CONTRIBUTING.md))

**Comment by aloneguid** [comment]
This is relatively easy to add. We should also extend parq tool to view metadata.

Do you mind sharing a use case why metadata is useful?

**Comment by SatyamG329** [comment]
Thanks, this will be really useful if you can please add this functionality. 
As the key-value in file metadata contains all column metadata in a wrapper struct. So in Impala we can create a table once, and refresh a table there onwards and this wrapper struct (key-value in file metadata) helps validates the existing table.
Hope this is useful.

**Comment by aloneguid** [comment]
Just so we are on the same page, are you expecting the schema metadata to be generated by parquet.net (like for instance Spark embeds it's own custom JSON schema, i'm not quite sure if it's used by anything else than Spark itself) or you are expecting to be able to add arbitrary metadata yourself from code?

**Comment by SatyamG329** [comment]
Hi, yes you are correct. 
After further studies, I've learnt custom JSON schema is not that useful. 
Thanks for all the help here, in regards to custom metadata, is it possible to add different Scales and Precision to DataTypes (for example when declaring Decimal DataField)?

**Comment by aloneguid** [comment]
Yes you can set custom precision and scales, as well as impala compatibility https://github.com/elastacloud/parquet-dotnet/blob/master/doc/schema.md#decimals

**Comment by ratulb87** [comment]
Hi Team,
I need to generate a Parquet schema with custom metadata on individual fields using Parquet.Net. Basically, when someone uses PySpark to read Parquet file schema, there is metdata attribute. For eg: {'type': 'struct', 'fields': [{'name': 'abc', 'type': 'string', 'nullable': True, 'metadata': {}}. I need to write values into metadata like { "des": "test desc", "sample value" : "sample"}. Does Parquet.Net support such feature? I downloaded the code and was unable to find this functionality. I am using Parquet.Net 3.3.9.
Thanks,

**Comment by aloneguid** [comment]
Released in v3.5.3, see a sample [here](https://github.com/aloneguid/parquet-dotnet/blob/develop/doc/writing.md#custom-metadata)
