### ISSUE TITLE
Migrate to Azure Pipelines

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#353]
We can run multi-OS tests much easier than with AppVeyor.

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by aloneguid** [comment]
Thanks @kaylangan. One showstopper for us is having a public pre-release nuget feed AppVeyor provides for free. Azure DevOps Artifacts seems to require some sort of licensing, unless I'm wrong?

**Comment by aloneguid** [comment]
@alexmullans looking forward to it. Yes please, i'll keep watching public announcements as well.
