### ISSUE TITLE
parq -m|--min: value is not an integer

### ISSUE THREAD

**Issue by eugeneniemand** [elastacloud/parquet-dotnet#356]
**Version:** parq 3.1.4 global install

**Runtime Version:** .Net Core 2.1.402

**OS:** Windows

#### Expected behavior

`parq view "C:\path-to-myfile" should display first 10 rows`

#### Actual behavior

Output
```
parq v3.1.4

-m|--min: value is not an integer
```

**Comment by aloneguid** [comment]
Duplicate of #351
