### ISSUE TITLE
ByteArray type throws NotImplementException on read

### ISSUE THREAD

**Issue by jaley** [elastacloud/parquet-dotnet#360]
**Version:** Parquet.Net v3.1.4

**Runtime Version:** .Net Framework v4.7

**OS:** Windows

#### Expected behavior

ByteArray fields round trip normally

#### Actual behavior

ByteArray fields cause a NotImplementException to be thrown at read time, though they seem to write OK.

### Steps to reproduce the behavior

1. Create a schema with a ByteArray type field 
2. Write a single row with a byte array as a value
3. Write to a new file
4. Open file and read into a table --> error is thrown

#### Code snippet reproducing the behavior

```fsharp
  [<Fact>]
  let ``ByteArrays roundtrip successfully``() = 
    TestHelpers.withTempFile (fun f ->
      let schema = Schema([DataField("bytes", DataType.ByteArray) :> Field])
      let tbl = Table(schema)
      tbl.Add(Row([|byte 0xff|]))

      let opts = ParquetOptions(TreatBigIntegersAsDates = false)
      let out = new FileStream(f, FileMode.OpenOrCreate)
      let writer = new ParquetWriter(schema, out, 
                                     formatOptions = opts, 
                                     append = false,
                                     CompressionMethod = CompressionMethod.Snappy)
      writer.Write(tbl)
      writer.Dispose()
      out.Close()

      use inp = new FileStream(f, FileMode.Open)
      use reader = new ParquetReader(inp)

      TestHelpers.assertEqual tbl <| reader.ReadAsTable()
    )
```

**Comment by aloneguid** [comment]
Thank you. Released in 3.2.2
