### ISSUE TITLE
List fields break Table equality

### ISSUE THREAD

**Issue by jaley** [elastacloud/parquet-dotnet#361]
**Version:** Parquet.Net v.3.1.4

**Runtime Version:** .Net Framework v4.7

**OS:** Windows

#### Expected behavior

`Table.Equals()` respects value semantics, and tables with equal content therefore return true.

#### Actual behavior

List fields seem always fail comparison. I'm guessing this is something to do with them being represented using arrays?

#### Code snippet reproducing the behavior

```fsharp
  [<Fact>]
  let ``Lists are comparable``() =
    let sch = Schema(ListField("ints", DataField("int", DataType.Int32, hasNulls=false)))
    
    let tbl1 = Table(sch)
    tbl1.Add(Row([| 1; 1; 1 |]))

    let tbl2 = Table(sch)
    tbl2.Add(Row([| 1; 1; 1 |]))

    Assert.True(tbl1.Equals(tbl2, true))
```

Exception thrown is as follows:

```
Message: System.ArgumentException : tables are different at row 0. this: {'ints': [1, 1, 1]}, other: {'ints': [1, 1, 1]}
---- System.ArgumentException : values are not equal at position 0 (System.Int32[] != System.Int32[])
```

**Comment by emlyn** [comment]
I think this will still fail with nested arrays? The `EqualTo` helper should check if `il` and `ir` are arrays and if so recurse into itself if so instead of calling `.Equals()`.
