### ISSUE TITLE
Is there a tangible way to stream from AWS S3?

### ISSUE THREAD

**Issue by martinkoslof** [elastacloud/parquet-dotnet#379]
Hello there, I'd like to start with, this library looks really awesome. I have downloaded the nuget package and I've written some prototypes which are very promising, however I was curious if anyone has used this with .net core in AWS via dockers, lambdas or serverless architecture?

Without getting into too much detail, we have a heavy data logic process which we are migrating. We are using AWS Glue to automate the process of generating parquet files and for some analytical needs such as reporting, leveraging Athena. The problem is, Athena can not support the level of concurrent queries and crunching that we need to do, and I'd prefer to just stream in the parquet files from S3 and use app logic to conduct the processing. Running local unit tests I'm getting remarkably fast results, but I'm obviously downloading the parquet files to my local c drive.

Are there any plans to integrate with S3? I realize Parquet isn't ideal for streaming since Meta data is located at the bottom of the file, but the requirement of a local disk is a show stopper for us. Has anyone been able to use S3 and this library together? We realize AWS Redshift Spectrum is another option but we've found nothing remotely as fast as shredding through the parquet file programmatically via this cool .net core library.

Thanks in advance for any advice or insight.

**Comment by martinkoslof** [comment]
I believe I have a workable solution. Our parquet files arent large, given they have already been broken into partitions. For example our main API will know to issue a request for = 60, and that points to an S3 hive partition. I have been successful so far at grabbing the parquet file from S3 and then wrappong the response stream in a seekable stream wrapper. I then provide that seekable stream to the ParquetReader and all tests have looked good.

**Comment by aloneguid** [comment]
@martinkoslof happy it worked for you. If you have a sample feel free to share.
