### ISSUE TITLE
Snappy compression doesn't seem to compress anything

### ISSUE THREAD

**Issue by tpeplow** [elastacloud/parquet-dotnet#380]
**Version:** Parquet.Net v4.0.3.0

**Runtime Version:** .Net Framework v4.5.2

**OS:** Windows

#### Background 

I looked at this sometime ago for a prototype and I'm picking this back up again as work to evolve our data formats.  We have an old application with a proprietary columnar format and we need to decide whether to maintain that or modernise.  I see the code base has moved on somewhat since I last got stuck in, which is great.

Write performance is a big deal, we run at considerable scale (typically tens of thousands of cores creating data which feeds into a downstream big data platform).  Our experience elsewhere lead us to the conclusion that Snappy CPU consumption & compression ratio is a lot cheaper than paying the extra for GZip (the compute cost takes a long time to be paid back given a few extra compression % points).  However, I'm not seeing what experience tells me I should see using Parquet.Net and Snappy.

As a side, compression has a huge impact as our data has a lot of repeating dimension values.  It seems there is no dictionary / RLE encoding of repeating string values, all the data reduction comes from the chosen codec.  This would be huge for us as dictionary encoding is cheap and will have benefits on the read side.  I see this issue (https://github.com/elastacloud/parquet-dotnet/issues/279), is there any movement on a way forward?

#### Expected behavior

Changing the CompressionMethod to Snappy results in a file which is larger than I would expect.  File result using GZip is ~27MB but it takes 00:06:52 to translate into Parquet, using Snappy the file is 183MB and takes 00:01:36 to translate.  If I take the parquet produced using CompressionMethod = Snappy and run that through a snappy compression stream of my own I get 30MB MB (no time overhead, snappy is bullet fast).

#### Actual behavior

I expect using Snappy CompressionMethod to yield a file in 30MB range not 183MB range.

### Steps to reproduce the behavior

I have a custom binary format file I'm converting into Parquet, when I run this with CompressionMethod = GZip I get compression, when I use Snappy I don't.  I can't share the real code but this example replicates the problem

```

_path = Path.Combine(Environment.CurrentDirectory, Guid.NewGuid() + ".parquet");

WriteFile(CompressionMethod.Snappy);
_snappyLength = new FileInfo(_path).Length;
System.Console.WriteLine(_snappyLength);

WriteFile(CompressionMethod.Gzip);
_gzipLength = new FileInfo(_path).Length;
System.Console.WriteLine(_gzipLength);

System.Console.WriteLine(_snappyLength / _gzipLength);

static void WriteFile(CompressionMethod compressionMethod)
{
    using (var file = File.Create(_path))
    {
        var schema = new Schema(new DataField<string>("field"));
        using (var parquetWriter = new ParquetWriter(schema, file) {CompressionMethod = compressionMethod})
        using (var rowGroup = parquetWriter.CreateRowGroup())
        {
            var data = Enumerable.Range(0, 1000).Select(x => "Value " + x).ToArray();
            rowGroup.WriteColumn(new DataColumn((DataField) schema.Fields[0], data));
        }
    }
}

```
Console output is:

5130
2253
2

**Comment by aloneguid** [comment]
@tpeplow I've just done a similar test and it seems to be OK. It could be already fixed in the latest version, can you please confirm?

```csharp
      [Fact]
      public void Temp()
      {
         Write(CompressionMethod.None);
         Write(CompressionMethod.Gzip);
         Write(CompressionMethod.Snappy);
      }

      private void Write(CompressionMethod method)
      {
         using (FileStream file = System.IO.File.Create($"c:\\tmp\\size-{method}.parquet"))
         {
            var schema = new Schema(new DataField<string>("field"));
            using (var parquetWriter = new ParquetWriter(schema, file) { CompressionMethod = method })
            using (var rowGroup = parquetWriter.CreateRowGroup())
            {
               var data = Enumerable.Range(0, 100000).Select(x => "Value " + x).ToArray();
               rowGroup.WriteColumn(new DataColumn((DataField)schema.Fields[0], data));
            }
         }
      }
```
![image](https://user-images.githubusercontent.com/3155189/51483912-1bc77d00-1d92-11e9-8b83-90d686e0a7b1.png)

**Comment by aloneguid** [comment]
In reagards to dictionary encoding, it's still on the backlog, we don't have any estimates when it will be done. However anyone is free to pick it up. There was experimental dictionary encoding in v2, however it worked only for strings and was extremely memory/cpu heavy.

**Comment by tpeplow** [comment]
@aloneguid sorry for delay - I'll have a look and get back to you in the next day or so

**Comment by tpeplow** [comment]
This looks good to me now!
