### ISSUE TITLE
List with one element doesn't work

### ISSUE THREAD

**Issue by lukred** [elastacloud/parquet-dotnet#381]
I'm using latest version 3.2.4.

Following the simplest repetition example from Parquet documentation:
https://blog.twitter.com/engineering/en_us/a/2013/dremel-made-simple-with-parquet.html
(see "Repetition levels" chapter).

I've created a code to reproduce their example:

 var idField = new DataField<int>("id");
            var idColumn = new DataColumn(idField, new int[] { 1, 2, 3 });

            var arrayField = new DataField("level2", DataType.String, isArray: true);
            var groupField = new ListField("level1", arrayField);

            var arrayColumn = new DataColumn(arrayField,
                new string[] { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j" },
                new[] {         0,   2,   2,   1,   2,   2,   2,   0,   1,   2 });

            var schema = new Schema(
                idColumn.Field,
                groupField
            );

Expected:

The second record should have two groups.

![obraz](https://user-images.githubusercontent.com/16718164/49803378-e6218400-fd4f-11e8-86a9-ec792f96e7ce.png)

Actual:

This is that I see from parq:
![obraz](https://user-images.githubusercontent.com/16718164/49803448-241ea800-fd50-11e8-981e-3aba398504d6.png)

**Comment by aloneguid** [comment]
Thanks for finding this. Yes seems like on repetition levels 0,1,2 there should be a new list created between 1->2 but it doesn't happen for some reason. Feel free to raise a PR for this.

**Comment by aloneguid** [comment]
fixed by @CurtHagenlocher
