### ISSUE TITLE
Reading a parquet file throws NullReference exception

### ISSUE THREAD

**Issue by lukred** [elastacloud/parquet-dotnet#383]
I have a parquet file successfully created by Parquet.net. 3,2,4
It has about 5 records with multiple columns (parquet file in the attachment).

When I want to read the content via your library, there is a null reference exception.

[test.zip](https://github.com/elastacloud/parquet-dotnet/files/2718040/test.zip)

This is the code I'm using to read the content:

```
 static IEnumerable<string> ParquetToJson(Stream stream) {
            var table = ParquetReader.ReadTableFromStream(stream);
            foreach (var row in table) {
                var record = row.ToString("j"); // it throws here!
                yield return record;
            } 
        }
```

**Expected behavior:**
If I created successfully this file using parquet.net I assume it's fine. 
I tried my best to check if the file is ok, and it seems it's ok. Unless you tell me it's not .

**Comment by dazfuller** [comment]
I've had a look at the test file and confirmed that is readable by Parquet.NET with the following code

```csharp
using (var reader = Parquet.ParquetReader.OpenFromFile("test.parquet", options))
{
    using (var rowGroupReader = reader.OpenRowGroupReader(0))
    {
        var dataField = reader.Schema.GetDataFields()
            .FirstOrDefault(df => df.Path == "geographic_location.list.geographic_location.name");

        if (dataField == null)
        {
            Console.WriteLine("Unable to locate column by path");
            return;
        }

        var data = rowGroupReader.ReadColumn(dataField);

        Console.WriteLine($"Data for {dataField.Path}");

        foreach (var item in data.Data)
        {
            Console.WriteLine(item);
        }
    }
}
```

This outputs the following from the file

```text
Data for geographic_location.list.geographic_location.name
French Guiana
Namibia
Albania

Botswana
Mauritania
```

The problem appears to be in the part of the library which builds the JSON string from the row, rather than how the data is read.

**Comment by dazfuller** [comment]
The parquet file is certainly readable from the limited bit I've seen so far, if you use the parq tool it will read the file, show the schema and the content.  I'd need to look at the rest of the data in there though to make sure it's all okay.
