### ISSUE TITLE
Parquet Reader Displays Dates With One Day Less

### ISSUE THREAD

**Issue by Rap70r** [elastacloud/parquet-dotnet#386]
**Version:** Parquet.Net v2.1.3

**Runtime Version:** .Net Framework

**OS:** Windows

#### Expected behavior

Using Parquet.Net v2.1.3 to read parquet files with date fields should bring the correct dates as it was inserted at the creation time.

#### Actual behavior

We are using Parquet.Net v2.1.3 to read parquet files. The problem is that when displaying the data, date fields are being displayed with one day less. We read the file using Spark and it gave correct dates. But when using Parquet.Net, with the same file, the dates are with one day less.

The left part is from the Parquet.Net and the right part is the correct data before creating the parquet.

<img width="272" alt="untitled" src="https://user-images.githubusercontent.com/22181358/50913187-cdb19180-1401-11e9-85a9-ac46d9879a93.png">

Can you please provide some help into how to solve this?

Thank you

**Comment by aloneguid** [comment]
Can you provide a sample file with the issue?

**Comment by aloneguid** [comment]
@Rap70r can you try v3.2.6 (latest from nuget), this might fix your issue.

**Comment by Rap70r** [comment]
Hi,
Using the latest version gives the same results.
We will provide a sample asap.

Thanks

**Comment by Rap70r** [comment]
Hi,
Here's a sample parquet file that displays the date with one day less when using Parquet.Net and the correct date when using Spark.

[hi.zip](https://github.com/elastacloud/parquet-dotnet/files/2750198/hi.zip)

**Comment by Rap70r** [comment]
Hello @aloneguid 

Did you have the chance to take a look at the file?
Can it be fixed using any kind of configuration?

File: [hi.zip](https://github.com/elastacloud/parquet-dotnet/files/2755402/hi.zip)

Regards

**Comment by aloneguid** [comment]
@Rap70r I think I found the issue, give me an hour.

**Comment by aloneguid** [comment]
@Rap70r I've released the fix in v3.3.1, please try.

**Comment by Rap70r** [comment]
Hello @aloneguid 

Thank you so much for the quick response.
By the way, there's no chance you can apply this fix to 2.1.3, right?

Regards
Saif

**Comment by aloneguid** [comment]
@Rap70r no problem ;)
It will be a lot of effort to fix 2.1.3 as we don't support it anymore for almost a year. Is there any reason you can't use v3?

**Comment by Rap70r** [comment]
Hello @aloneguid 

No worries. We will re-write our solution.
Thank you for the fix.

Regards

**Comment by Rap70r** [comment]
Hello @aloneguid 

Looks like the issue has been resolved.

Thank you
