### ISSUE TITLE
JSON Convert the whole Table

### ISSUE THREAD

**Issue by AnisTss** [elastacloud/parquet-dotnet#393]
**Version:** Parquet.Net v3.2.5

**Runtime Version:** .Net Core v 2.1

**OS:** Windows

#### Expected behavior

Easily convert a complete Table to JSON

#### Actual behavior

I cannot find a trivial method that serializes a Table object into JSON string. The .ToString("j") is doing well except for the 10 rows limitation. It would be nice if the ToString() would serialize a complete table into JSON. I suggests introducing a boolean **truncate** parameter, true by default, that would enable/disable the 10 rows limit. (also an **n** int parameter for the limit)

Inspired from [here](http://spark.apache.org/docs/2.1.0/api/python/pyspark.sql.html#pyspark.sql.DataFrame.show)

**Comment by aloneguid** [comment]
Should be trivial to do, are you happy to raise a PR?

**Comment by AnisTss** [comment]
@aloneguid Sure ! i will work on it as soon as i get some free time from my current task ;)

**Comment by aloneguid** [comment]
@AnisTss yes this must be a bug. I think it was first used in CLI, which serialises data row by row and takes into account command line parameter. By default it should only take a small amount of rows (like 10) because ToString is used widely in debugger for instance and trying to convert a truly large dataset will just freeze your IDE ;)

**Comment by aloneguid** [comment]
@AnisTss just checking you're working on this.

**Comment by AnisTss** [comment]
@aloneguid I am sorry, I was not active on GitHub lately. I do really have urgent matters at work I can't really contribute. But, it should be easy to implement.

Btw, why closing all issues ? are you planning to close-source this project ?
