### ISSUE TITLE
Bad Boolean Serialization

### ISSUE THREAD

**Issue by AnisTss** [elastacloud/parquet-dotnet#394]
**Version:** Parquet.Net v3.2.5

**Runtime Version:** .Net Core v 2.1

**OS:** Windows 10

#### Expected behavior

JSON Serialization should serialize boolean values as lowercase. 

#### Actual behavior

JSON Serialization serializes boolean values with first character as Uppercase. (false --> False, true --> True).
The issue is somewhere over [here](https://github.com/elastacloud/parquet-dotnet/blob/49875e0e932336dd55e358f0b4ca241040fe9fed/src/Parquet/Extensions/StringBuilderExtensions.cs#L122) boolean.ToString() returns "False" or "True".

**Comment by aloneguid** [comment]
already fixed by @CurtHagenlocher
