### ISSUE TITLE
parq output to CSV

### ISSUE THREAD

**Issue by mcmillab** [elastacloud/parquet-dotnet#395]
you asked for suggestions for the parq command:

Output to CSV would be very useful. I recocognize that parquet can have more complex datasets that CSVs generally allow for, however lots of the parquet datasets can easily be converted to CSV.

Maybe even with an optional range: ie, if the dataset is a timeseries, output between 2 dates... or output between 2 row numbers.

**Comment by aloneguid** [comment]
It should be easy to implement, as long as the data is flat as you say. CSV and/or T-CSV. CSV also tends to be faster than JSON in raw read/write speeds.

Ranges will be harder to do, mostly needs a though how they will be exposed via command line.

**Comment by aloneguid** [comment]
we can output to CSV as long as parquet file doens't have complex types, or simply skip complex types, is that acceptable?

**Comment by mcmillab** [comment]
definitely

**Comment by aloneguid** [comment]
This is implemented in development branch. Refer to aloneguid/parquet-dotnet#19 to track progress.
