### ISSUE TITLE
Empty Values in nested list

### ISSUE THREAD

**Issue by AnisTss** [elastacloud/parquet-dotnet#398]
**Version:** Parquet.Net v3.2.5

**Runtime Version:** .Net Core v2.1

**OS:** Windows 10

#### Expected behavior

I use parquet dotnet to read mllib models written by spark. I expect the same behavior as the parquet-mr (as i know used by spark)

#### Actual behavior
I have the parquet file bellow that has a DecisionTreeClassificationModel data.
[modelData.zip](https://github.com/elastacloud/parquet-dotnet/files/2808972/modelData.zip)

The `leftCategoriesOrThreshold` property should have values in my case. However the CLI displays it as an empty list.

![image](https://user-images.githubusercontent.com/11518540/51928522-71390500-23f6-11e9-998c-a1092d0dfa01.png)

I tried to debug the project using a simple console app that reads that single file as a table. And checked some method calls. The screenshot below shows that the `Dictionnary<string, LazyColumnEnumerator>` of the method `TryBuildListCell` has already the data i need. But, it is having a bad time transforming it into rows.

![image](https://user-images.githubusercontent.com/11518540/51929432-80b94d80-23f8-11e9-834e-dee3a1f1bdb4.png)

*Note: nevermind that `var list = pathToColumn.ToList();` in the screenshot i was just using it for debugging*

**Comment by aloneguid** [comment]
Because of the nature of opensource I can't estimate how long it will take, it all depends on availability of free time (we all have day jobs). You are welcome to fix it yourself and raise a PR if time is a pressure or contact parquetsupport@elastacloud.com for priority support options.

**Comment by aloneguid** [comment]
Hi @AnisTss I've just release v3.3.3 with a fix for this. Please reopen if you have any issues. Thanks for reporting it.
