### ISSUE TITLE
NULL value handing in reader

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#4]
Not entirely sure how to read null values, it has something to do with definition/repetition levels in data page.

**Comment by aloneguid** [comment]
Actually this is quite important as our reader will crash when handling null values, so moving to Phase 1.

**Comment by aloneguid** [comment]
@azurecoder we can store indexes for definition levels inside ParquetColumn, that way it's RAM efficient and can be transformed to nullable types when client iterates Values collection. What do you think?

**Comment by azurecoder** [comment]
Completed but needs more and different testing to check integrity of output
