### ISSUE TITLE
INT96 is marked as deprecated

### ISSUE THREAD

**Issue by mgolen** [elastacloud/parquet-dotnet#417]
Hi everyone,

According to https://issues.apache.org/jira/browse/PARQUET-323 type INT96 is deprecated.
However, DateTime and DateTimeOffset are serialized to INT96.

Are there any plans to mitigate this problem?
Should I use DateTimeOffset.ToUnixTimeMilliseconds() and serialize value as INT64 as a recommended workaround?
Thanks in advance.

**Comment by iainb123** [comment]
I had the same issue.  You can create a DateTimeDataField rather than a DataField<T> and specify DateTimeFormat.DateAndTime to use a 64-bit timestamp.

**Comment by aloneguid** [comment]
@iainb123 is correct, INT96 is used for backward compatibility reasons as many readers won't undestand 64-bit timestamp.
