### ISSUE TITLE
ParquetConvert Deserialize doesn't work with ParquetColumn

### ISSUE THREAD

**Issue by dancsharp** [elastacloud/parquet-dotnet#418]
I am not able to use ParquetConvert.Deserialize when ParquetColumnAttribute is leveraged.  One way to reproduce is to update the following unit test:

Add the following attribute to the Name property of SimpleStructure.cs, found in ParquetConvertTest.cs, and the unit test Parquet.Test.Serialisation.Serialise_deserialise_all_types will throw a NullReferenceException:

[ParquetColumn("someothername")]
public string Name { get; set; }

Object reference not set to an instance of an object.
Stack Trace:
   at Parquet.Serialization.Values.MSILGenerator.GenerateAssigner(DataColumn dataColumn, Type classType) in /tmp/parquet-dotnet-master/src/Parquet/Serialization/Values/MSILGenerator.cs:line 156

**Comment by david-nguyen** [comment]
Can confirm I'm having the same issue.

**Comment by aloneguid** [comment]
Confirmed it a bug, fix is coming. Refer to aloneguid/parquet-dotnet#29 to track progress.
