### ISSUE TITLE
ParquetConvert Serializer could take filePath/stream/streamReader instead

### ISSUE THREAD

**Issue by rbx44** [elastacloud/parquet-dotnet#428]
ParquetConvert Serialize takes an IEnumerable and with Schema optional. Is it possible to have an overload which takes Schema (not optional) and Stream/StreamReader? Converting CSV to Parquet is painful since we first have to serialize CSV to an object.

**Comment by aloneguid** [comment]
Why not using ParquetReader / ParquetWriter?

**Comment by rbx44** [comment]
How do I specify DataColumn with stream when I use ParquetRowGroupWriter.WriteColumn()?

**Comment by rbx44** [comment]
![image](https://user-images.githubusercontent.com/8643739/62903238-9f918880-bd27-11e9-8768-6b6c0f80b388.png)
 schema.Fields is of type field, DataColumn expects DataField and an array. I will need to serialize csv to object anyway or am I missing something?

**Comment by aloneguid** [comment]
No, you cannot stream CSV to Parquet, because the first one is row based and the second one is columnar. You'll have to load the entire CSV in memory, split in columns and then convert to Parquet.
