### ISSUE TITLE
Cannot open parquet files created with Parquet.JS

### ISSUE THREAD

**Issue by mukunku** [elastacloud/parquet-dotnet#429]
**Version:** Parquet.Net v3.3.8

**Runtime Version:** .Net Framework v4.6.1

**OS:** Windows

### Expected behavior

Read data column from Row Group.

### Actual behavior

Null reference exception.

### Steps to reproduce the behavior

1. Create new Node project and add the [Parquet.JS](https://github.com/ironSource/parquetjs) library
2. Create a new parquet file with primitive types such as string and int.
3. Try reading any data column from the parquet file using Parquet.Net

### Code snippet reproducing the behavior

**Code used to generate the parquet file:**
![62872638-81a23480-bce3-11e9-95ea-0ffe7439476c](https://user-images.githubusercontent.com/4502154/62976463-a0d7b980-bdea-11e9-9f37-ee2ff1c88e35.png)

**Code to read the parquet file:**
```
using (var parquetReader = ParquetReader.OpenFromFile("C:/sample.parquet", new ParquetOptions() { TreatByteArrayAsString = true }))
{
    for (int i = 0; i < parquetReader.RowGroupCount; i++)
    {
        using (ParquetRowGroupReader groupReader = parquetReader.OpenRowGroupReader(i))
        {
            foreach(var field in parquetReader.Schema.GetDataFields())
            {
                var column = groupReader.ReadColumn(field); //throws error for every field
            }
        }
    }
}
```

**Sample parquet file:** [sample.zip](https://github.com/elastacloud/parquet-dotnet/files/3505803/sample.zip)

**Comment by aloneguid** [comment]
The file is corrupt as it's missing data page header. It also cannot be read with native java tools either:

![image](https://user-images.githubusercontent.com/3155189/63102192-8a5c6a00-bf72-11e9-9a54-a2878fb6764d.png)

I've added a fix to throw better exception in this case.

**Comment by mukunku** [comment]
Thanks for looking into this.

**Comment by jvasekpn** [comment]
Thank you for helping me get to the bottom of this.  The example parquet file posted above works fine with pyarrow and in AWS Athena, so they must have some graceful way of loading the data although it's malformed.

**Comment by aloneguid** [comment]
Thanks I will investigate in future. The file won't open in Spark though therefore it might make sense to fix it on is side too.
