### ISSUE TITLE
Conflicting Documentation/Recommendations for Writing Parquet

### ISSUE THREAD

**Issue by martinkoslof** [elastacloud/parquet-dotnet#431]
Hello, I've been using this library to read in and parse existing Parquet files we generate via AWS Glue for a processing engine API. I've been very satisfied with the quality of the library! Now, I'm working on the export engine aspect, which more or less is pushing csv, json and parquet formatted results. Some of my generated models are large (over 1 million rows and 8-14 columns) and I want to create the most efficient parquet files I can (regarding the performance of the generation process and external systems reading it).

Looking at the documentation for writing files, I believe there is a typo somewhere. Initially, the documentation says:

"When required, repeat from step (2) to create more row groups. It's not recommended to have more than 5'000 rows in a single row group for performance reasons."

So, this says it is NOT recommended to have more than 5,000 rows in a single row group. This seems odd to me, and I'm further confused when further down, it's contradicted (where it discusses appending):

"Please keep in mind that row groups are designed to hold a large amount of data (5'0000 rows on average) therefore try to find a large enough batch to append to the file. Do not treat parquet file as a row stream by creating a row group and placing 1-2 rows in it, because this will both increase file size massively and cause a huge performance degradation for a client reading such a file."

So this says row groups are designed to hold 50,000 row on average, and use larger batches...

What is the real best practice here for generating a parquet file which will have over 500,000 rows and normally never more than 1.3 million?

Thanks

**Comment by telferm57** [comment]
I was about to raise the same issue ! I am using systme consuming parquet files that expect rowgroups to be around 64MB as a minimum , which would point to a rowgroup  size of 50k records rather than 5k .... but in fact  100k or greater would be appropriate in many cases

**Comment by aloneguid** [comment]
I think the original documentation is taking into account HDFS, so storing on different systems can have completely different recommendations.
