### ISSUE TITLE
ClrBridge.BuildColumn failed with NullReferenceException when ParquetConvert.Serialization called in parallel

### ISSUE THREAD

**Issue by leonidzh** [elastacloud/parquet-dotnet#432]
**Version:** Parquet.Net version 3.3.9

**Runtime Version:** .Net Framework v, .Net Core v2.2

**OS:** Windows/Linux/MacOSX v NA

#### Expected behavior

ParquetConvert.Serialization() method should be thread safe

#### Actual behavior

ParquetConvert.Serialization() method fails with NullReferenceException as a result of simultaneous call from different threads. This happens rarely but enough for data lost.

### Steps to reproduce the behavior

1. Run Parquet.Serialization() in a few threads (I have 3-4) for different streams and schemes
2. Wait for a failure (it might take 1-2 hours)

#### Code snippet reproducing the behavior
NA
#### Proposed fix (I'm going to do that)
Class ClrBridge has two static dictionaries that cause the issue. There are two options - remove static, but this can have some performance impact, or change their type to ConcurrentDictionary (I prefer this one)

**Comment by aloneguid** [comment]
I don't think we have Parquet.Serialization() method, please provide a reproducible code sample.

**Comment by leonidzh** [comment]
Fixed, sorry for typo.
I also can provide fix as I suggested by end of September.
