### ISSUE TITLE
Need ability to write custom metadata (key:value) for DataField

### ISSUE THREAD

**Issue by ratulb87** [elastacloud/parquet-dotnet#433]
Hi Team,
I have a scenario where I am generating Parquet file using Parquet.Net. This Parquet file will be consumed by a System that uses PySpark. In PySpark, when the read the file schema, the schema json for the fields is read as [{'name': 'abc', 'type': 'string', 'nullable': True, 'metadata': {}}, {'name': 'def', 'type': 'string', 'nullable': True, 'metadata': {} }, {'name': 'xyz', 'type': 'decimal(38,18)', 'nullable': True, 'metadata': {}}]. I am looking for the ability to populate the metadata attribute as 
metadata: {'desc':'sample desc' , 'comment' : 'sample comment'}. I downloaded the code base for Parquet.Net and tried to populate the values in Column Chunk's ColumnMetaData key value pairs but that did not seem to work. Can we get this functionality added?
Thanks,
Ratul

**Comment by aloneguid** [comment]
ParquetWriter/Reader has metadata field you can write/read.

**Comment by ratulb87** [comment]
@aloneguid Thanks for your reply. I am still not sure which meta data field you are referring to. I have never worked with parquet files before. I need different meta data for each column. Something like
 [{'name': 'abc', 'type': 'string', 'nullable': True, 'metadata': {'desc':'sample desc' , 'comment' : 'sample comment'}}, {'name': 'def', 'type': 'string', 'nullable': True, 'metadata': {'desc':'sample desc 1' , 'comment' : 'sample comment 1'} }, {'name': 'xyz', 'type': 'decimal(38,18)', 'nullable': True, 'metadata': {'desc':'sample desc 2' , 'comment' : 'sample comment 2'}}]

**Comment by aloneguid** [comment]
Parquet.Net supports file metadata only, as there is no such thing as column metadata. The format itself allows to assign metadata per column chunk, meaning each column can have many chunks with totally different metadata in every row group. I'm not quite sure what pyspark code you've shown will do, is it going to write the same metadata in all column chunks and all row groups, or is it just the first one? In any way the behaviour is inconclusive.

**Comment by ratulb87** [comment]
I am actually trying to read the schema using PySpark
df = spark.read.parquet(Input_ParquetFile)
schema_json = df.schema.jsonValue()

This outputs the schema as
StructType([
StructField(name='a_field', dataType=IntegerType(), nullable=False, metadata={}),
StructField(name='b_field', dataType=StringType(), nullable=True, metadata={})
])

I am assuming this indicates meta data at column chunk level. I was trying to see how to populate this meta data in the schema for files generated using Parquet.Net. As per your previous comment, it seems Parquet.Net only allows meta data at file level. Thanks for the clarification.

**Comment by tjippasma** [comment]
I would also like to add custom metadata (filemetadata). I see the "CustomMetadata" property on ThriftFooter and beleive thats the one to use, only problem is that this property is hidden (private) with the current api

**Comment by aloneguid** [comment]
Latest version has CustomMetadata on both ParquetReader/Writer.

**Comment by ddalalrms** [comment]
I'm having a hard time adding CustomMetada to a parquet file. Let's say I have a parquet file with some schema and a bunch of rows. I want to write new metadata to that file. Do you have an example of how this would work?

**Comment by JD-Robbs** [comment]
But the `CustomMetadata` property on  `ParquetWriter` has the type `IReadOnlyDictionary` - how can you change/add any of the values and how would these changes be committed to the file?

**Comment by AtricoSoftware** [comment]
> But the `CustomMetadata` property on `ParquetWriter` has the type `IReadOnlyDictionary` - how can you change/add any of the values and how would these changes be committed to the file?
> 

The property type is IReadOnlyDictionary but the property itself is writable.  Create your own dictionary and assign it.  I have tested this and it works fine.
I think it would be good to be able to write the equivalent custom metadata in column chunks though. I require metadata for each column, whilst I can encode this at file level it will be a little cumbersome.
I think that the column metadata should be copied to each chunk for the column, this will allow the reader to skip chunks without losing the metadata.
