### ISSUE TITLE
Write speed improvement for compressed parquet

### ISSUE THREAD

**Issue by xingchen517** [elastacloud/parquet-dotnet#436]
Hi Team,
Suggesstions:
1 Could you please expose the configuration for gzip CompressionLevel?
2 For Parquet.File.DataColumnWriter.WriteColumn, the GzipStream would be called every time for each value in each column, this would make the process slow, it would be very fast if you make it write first to a BufferStream then write it to GzipStream.
I tried the two things and it gave me 4x faster than before.
Thanks

**Comment by aloneguid** [comment]
Yes makes perfect sense.

**Comment by aloneguid** [comment]
working on it

**Comment by aloneguid** [comment]
you can [specify compression level](https://github.com/aloneguid/parquet-dotnet/blob/master/doc/writing.md#specifying-compression-method) now in v3.4.2

**Comment by aloneguid** [comment]
closing and creating a new issue for BufferedStream
