### ISSUE TITLE
Writing NULL values to parquet

### ISSUE THREAD

**Issue by cvkem** [elastacloud/parquet-dotnet#438]
**Version:** Parquet.Net  Build based on last weeks repo

**Runtime Version:** .Net Framework 4.5

**OS:** Windows

I'm intending to dump a database-table to a Parquet file for compact transport. This works fine as long as the tabel does not contain NULL values. In the passed we used the Row-based API which operated fine with NULL values. However, as tables grow we need to move to the default Column-based API as this is more efficient in terms of memory and in terms of speed. However, in this API I can not find how to work with NULL-values. For Strings this works fine. NULL values are translated to empty-strings, which is a little loss of information, but I think this is as expected in Parquet. However, , but for Int64 we can not make it work. I tried several options:

1. Passing in Nullable`1[System.Int64] arrays with null-values with a NULL for the repetition-levels
2. Passing in Nullable`1[System.Int64] arrays with null-values with an all zero's array for the repetition-levels  
3. Passing in a System.Int64 array with non-null values only and adding in a definition-levels array with 1 for values and 0 for null-values. (had to change a DataColumn constructor from 'internal' to 'public' to make this work. 

When looking at the empty-arrays section of the chapter on 'Complex types' in the readme I see that I did everything to get to the solution suggested over there (but then with an all nulls array for the repetition level as we don't have more than one value in a single row).
This  documentation says that if you want to encode:
[1 2]
[]
[3 4]

this is encoded as
values:             [1 2 null 3 4]
repetition levels:  [0 1 0    0 1]

However, I want to encode
[1]
[2]
[]
[3]
[4]

So that should be 
values                 [1 2 null 3 4]
repetition levels   [0 0  0   0 0]

However, the file that comes out is not readible (not with the current parquet-dotnet and also not via the v2.0.0.0 version we have been using for years.

Below you find the stack-trace and the zipped parquet-file as an attachment.

**the stack-trace when reading tst4a.pq**

EndOfStreamException Unable to read beyond the end of the stream.
        System.IO.BinaryReader.FillBuffer (:0)
        System.IO.BinaryReader.ReadDouble (:0)
        Parquet.Data.Concrete.DoubleDataTypeHandler.ReadSingle (:0)
        Parquet.Data.BasicDataTypeHandler`1.Read (:0)
        Parquet.Data.BasicDataTypeHandler`1.Read (:0)
        Parquet.File.DataColumnReader.ReadColumn (:0)
        Parquet.File.DataColumnReader.ReadDataPage (:0)
        Parquet.File.DataColumnReader.Read (:0)
        Parquet.ParquetRowGroupReader.ReadColumn (:0)
        Parquet.ParquetExtensions+<>c__DisplayClass3_0.<ReadAsTable>b__0 (:0)
        System.Linq.Enumerable+WhereSelectArrayIterator`2.MoveNext (:0)
        System.Linq.Buffer`1..ctor (:0)

[tst4a.zip](https://github.com/elastacloud/parquet-dotnet/files/3855462/tst4a.zip)

 **build issue for .net45**
PS: We had to build the library from sources as the Nuget download got us in trouble due to missing System.Buffers v4.0.3.0 and System.Memory v4.0.1.0. Possibly these references are located in Thrift v0.9.2.0 which also could not be found. However, a build from sources with a net45 framework provided a dll folder with these dependencies

**Comment by aloneguid** [comment]
Thanks for raising the issue, can you include reproducible code sample? That would speed up investigation greatly.

**Comment by cvkem** [comment]
All my tests and experiments were done in Clojure-clr which is a variant of the Clojure language that runs on the .NET engine. For that reason my source-code probably is not going to help you very much as it is not plain C# code. 
However, if you can tell me the correct method for encoding a NULL value then it would already help a lot, and I will probably be able to make a piece of example showing it works or that it does not work. As mentioned I tried 3 things:
1. Just passing in an array  C# Nullable-integers and using that to encode NULL
2. ... a variant on the above
3. Passing in an Object-array which contains integers and NULL values

What is the shape of the data-array that I need to pass in? An array of Objects or an array of Nullable Integers in case of an Integer column?

**Comment by aloneguid** [comment]
@cvkem let me get it clear, are you trying to write a column of primitive type (nullable int64) or a column of arrays of primitive types (each cell is a nullable array)?

In the first case, yo don't need to specify *repetition* levels, here is [an example](https://github.com/aloneguid/parquet-dotnet/blob/901ccc05cc586d80ceeaef50b5e4abf04e17f6db/src/Parquet.Test/ParquetWriterTest.cs#L139), `DataColumn` will create *definition* levels for you.

**Comment by cvkem** [comment]
@aloneguid  I did use a plain array of nullable int64. So I did not use nested arrays.

thanks for the concrete test-case/example I will put my code next to it tomorrow.
I assume that Array is an array of type (nullable int64) in the method below:
 public void Write_read_nullable_column(Array input) 

Thanks!

**Comment by aloneguid** [comment]
no problem @cvkem feel free to reopen if you need more help

**Comment by cvkem** [comment]
Ivan,

Thanks for the suggestions including a pointer to the test-case/example, it
helped us solve the problem.

Cees.

**Comment by aloneguid** [comment]
Glad I could help )
