### ISSUE TITLE
[Q] Compression effeciency: Parquet.Net vs AWS Glue ETL Job

### ISSUE THREAD

**Issue by kirsar** [elastacloud/parquet-dotnet#439]
**Version:** Parquet.Net v3.3.9

**Runtime Version:** .Net Core v2.1

**OS:** Windows 10.

#### Expected behavior

Parquet.Net doesn't compress as cool as AWS Glue Job does

#### Actual behavior

Having csv file of 150Mb with several empty string columns and columns with single value for all cells, AWS Glue ETL Job compresses it to 26Mb and my custom code, based on Parquet.Net compresses it to 55Mb. 
1. I do use ParquetRowGroupWriter with 50K rows per group (AWS writes entire file to the single group, but making so doesn't make any difference for the compression ratio)
2. I checked that empty strings are comressed properly - making it non-empty increases compressed file size to 107Mb.

May be one can see the way I can setup compression to reach the compression ratio AWS has?

**Comment by aloneguid** [comment]
which compression/encoding are you using in both?

**Comment by kirsar** [comment]
snappy

And here is source and both results

[source-and-results.zip](https://github.com/elastacloud/parquet-dotnet/files/3887071/source-and-results.zip)

**Comment by aloneguid** [comment]
@kirsar snappy implementation isn't great in parquet.net, it's using a very old abandoned OSS library, needs to be improved sooner rather than later. Does anyone have suggestions for a good Snappy implementation that doens't have any native dependencies?

**Comment by kirsar** [comment]
@aloneguid Thanks! At least I know I did best to improve the ratio.
