### ISSUE TITLE
Set sorting columns on row group

### ISSUE THREAD

**Issue by KyleGobel** [elastacloud/parquet-dotnet#442]
In the row group metadata there are some fields that specify how the data is sorted.

Are there any plans to expose this for reading or writing?

In my work I often have to join different files or row groups, knowing if I can do a merge join or not without sorting all the data first is very helpful.

**Comment by aloneguid** [comment]
`ParquetReader` has `ThriftMetadata` member that gives low-level access to parquet metadata, does this give enough info?

**Comment by KyleGobel** [comment]
It's contained within the actual row group: [Sorting Columns in RowGroup.cs](https://github.com/elastacloud/parquet-dotnet/blob/master/src/Parquet/Thrift/RowGroup.cs#L35)

On a local branch I exposed this via the `ParquetRowGroupReader` similar to how the `RowCount` was done: [RowCount in ParquetRowGroupReader.cs](https://github.com/elastacloud/parquet-dotnet/blob/master/src/Parquet/ParquetRowGroupReader.cs#L44)

Maybe on the `ParquetRowGroupReader` something like `ThriftRowGroup` could be made a public read only property?

I think the same thing would actually work for the `ParquetRowGroupWriter` too? (exposing the ThriftRowGroup), except on the writer it'd have to be writable.

**Comment by KyleGobel** [comment]
Hmm, but I see the `RowGroups` are on the `FileMetaData`, didn't see that before...so I guess that probably would work and be enough I think, I'll try that out.

**Comment by aloneguid** [comment]
Thanks see if it help, if not I can add some helper method on `RowGroupReader`

**Comment by KyleGobel** [comment]
Thanks, the `ThriftMetadata` works good for reading that data in, is there any recommended way to write that data?

I can hack it and get the private field `_thriftRowGroup` for the `RowGroupWriter` with reflection and write to that which appears to work just fine, thought i'd ask though if there's a more 'supported' way to do this.

```cs
using var writer = new ParquetWriter(...);
using var rgw = writer.CreateRowGroup();

var rowGroup = typeof(ParquetRowGroupWriter)
    .GetField("_thriftRowGroup", BindingFlags.Instance | BindingFlags.NonPublic)
    .GetValue(rgw) as Thrift.RowGroup;

rowGroup.Sorting_columns = new List<Thrift.SortingColumn> { ... };

rgw.WriteWriteColumn(...);
```

**Comment by aloneguid** [comment]
Thrift metadata was intentionally made read-only as it's somewhat sensitive, any wrong bit may cause reader to fail. We could make it public and push the responsibility to the user, however I'd personally prefer safe helper methods. Happy for you to come up with some in a PR, or suggest here?
