### ISSUE TITLE
Parquet Schema Serialization 

### ISSUE THREAD

**Issue by nabdelmallek** [elastacloud/parquet-dotnet#443]
**Version:** Parquet.Net v3.3.3

**Runtime Version:** .Net Core v2.2

**OS:** Windows 10.

#### Expected behavior
Read Parquet file in its correct schema. 
PS: The Parquet file is a Decision Tree Classification Model generated by spark. 

#### Actual behavior
I have generated the following DecisionTreeClassification Models by spark: 
[doesntWork.snappy.zip](https://github.com/elastacloud/parquet-dotnet/files/4012772/doesntWork.snappy.zip), [works.snappy.zip](https://github.com/elastacloud/parquet-dotnet/files/4012773/works.snappy.zip)
 In fact, while I try to read the "doesntWork" example I don't get the correct schema of the data. I'm supposed to get the following schema (PS: Tested with "works" example)
![image](https://user-images.githubusercontent.com/55890920/71623324-f49d4080-2bdb-11ea-89ce-8a869790f29a.png)
Whereas, I'm actually getting this schema : 
![image](https://user-images.githubusercontent.com/55890920/71623374-6aa1a780-2bdc-11ea-9d34-c584b2d61d67.png)
It seems like it is merging the impurityStats and gain columns.
And this is the exception that I got : **'impurityStats.array.gain' does not exist in this file**.
 I have tried to read the "doesntWork" example with another parquet reader and it works.

**Comment by aloneguid** [comment]
could you add a reproducible code sample? struggling to understand what's not working

**Comment by nabdelmallek** [comment]
Here is the code 
[ReadParquet.zip](https://github.com/elastacloud/parquet-dotnet/files/4018857/ReadParquet.zip)

**Comment by aloneguid** [comment]
@nabdelmallek the solution fails with
```
System.IO.FileNotFoundException: 'Could not find file 'C:\tmp\ReadParquet\bin\Debug\netcoreapp2.2\UseAttachedFilePath(DoesntWork)'.'
```
Something I need to put there?

**Comment by nabdelmallek** [comment]
yes u need to upload this parquet file 
[doesntWork.snappy.zip](https://github.com/elastacloud/parquet-dotnet/files/4035294/doesntWork.snappy.zip) and put its path

**Comment by aloneguid** [comment]
Thanks, got it, seems like a bug. Parquet.Net thinks 'gain' field is a member of the list:

![image](https://user-images.githubusercontent.com/3155189/72528227-78089400-3862-11ea-9c1a-0dae0f13dde7.png)

however, it's a root field as read by parquet-mr:

```
row group 1:                RC:7 TS:956 OFFSET:4
--------------------------------------------------------------------------------
id:                          INT32 SNAPPY DO:0 FPO:4 SZ:63/61/0.97 VC:7 ENC:BIT_PACKED,PLAIN
prediction:                  DOUBLE SNAPPY DO:0 FPO:67 SZ:77/73/0.95 VC:7 ENC:BIT_PACKED,PLAIN_DICTIONARY
impurity:                    DOUBLE SNAPPY DO:0 FPO:144 SZ:97/97/1.00 VC:7 ENC:BIT_PACKED,PLAIN
impurityStats:
.array:                      DOUBLE SNAPPY DO:0 FPO:241 SZ:211/271/1.28 VC:168 ENC:RLE,PLAIN_DICTIONARY
gain:                        DOUBLE SNAPPY DO:0 FPO:452 SZ:109/107/0.98 VC:7 ENC:BIT_PACKED,PLAIN_DICTIONARY
leftChild:                   INT32 SNAPPY DO:0 FPO:561 SZ:63/61/0.97 VC:7 ENC:BIT_PACKED,PLAIN
rightChild:                  INT32 SNAPPY DO:0 FPO:624 SZ:63/61/0.97 VC:7 ENC:BIT_PACKED,PLAIN
split:
.featureIndex:               INT32 SNAPPY DO:0 FPO:687 SZ:72/68/0.94 VC:7 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY
.leftCategoriesOrThreshold:
..array:                     DOUBLE SNAPPY DO:0 FPO:759 SZ:84/94/1.12 VC:7 ENC:PLAIN,RLE
.numCategories:              INT32 SNAPPY DO:0 FPO:843 SZ:67/63/0.94 VC:7 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY
```

**Comment by aloneguid** [comment]
Fixed in development branch. Refer to aloneguid/parquet-dotnet#22 to track progress.
