### ISSUE TITLE
What is the current official repository?

### ISSUE THREAD

**Issue by oyse** [elastacloud/parquet-dotnet#460]
Is this the offical repository for the package or is it https://github.com/aloneguid/parquet-dotnet ?

If the official repository has moved please provide some information about that in the README file.

**Comment by nsulikowski** [comment]
I posted the mirror question in aloneguid...

**Comment by skyyearxp** [comment]
i think the main project is maintained on alonguid/parquet-dotnet now.
you can search nuget, find Parquet.Net and look at the version history.
before v3.4.0 the projet url is https://github.com/elastacloud/parquet-dotnet
after 3.4.1 the project url is https://github.com/aloneguid/parquet-dotnet
so be it. :)

**Comment by nsulikowski** [comment]
Makes sense
