### ISSUE TITLE
Can't read a page of strings in plain encoding

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#48]
@azurecoder i'm not sure why we are trying to cast values to bool, must be a bug?

![image](https://user-images.githubusercontent.com/3155189/27629336-edba65be-5be9-11e7-886d-08e6c6d191aa.png)

**Comment by azurecoder** [comment]
gah! that's doomed! I can look at tonight when I'm back at the hotel

**Comment by aloneguid** [comment]
@azurecoder I think I got it fixed by removing a cast, at least none of the tests are failing.
