### ISSUE TITLE
Proposal - work with plain (non-nullable) lists from IValuesReader

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#61]
Here is the problem.

When working with normal (non-nullable) columns the result gets returned as a list of nullable types. THis is OK but is a bit confusing as underlying type is not nullable. It also has performance impact on reading.

On the other hand, when type is nullable, IValuesReader first reads it in a nullable list, and then it gets reconstructed again taking into account definition levels, which again takes time.

**Comment by azurecoder** [comment]
Yeah, this was just a first stab so that we could captures NULLs, it really doesn't make sense to do this at all generally and is confusing for a consumer. The Require property is that indicative of null or not, can't remember?

**Comment by aloneguid** [comment]
@azurecoder yes it's a type of repetition level, if set to Required than definition levels are missing and no nulls allowed. I've noticed this is extremely inconvenient for writing, when creating dataset from scratch

**Comment by azurecoder** [comment]
Have updated and tested, approve PR if happy
