### ISSUE TITLE
Formatted output in parq client

### ISSUE THREAD

**Issue by azurecoder** [elastacloud/parquet-dotnet#62]
A formatted output is needed in parq console application which will display the first n rows spaced to fit a console window in a console grid with the number of rows affected after the table output.

**Comment by AndyCross** [comment]
Feedback requested on initial formatted grid

![image](https://user-images.githubusercontent.com/773613/27818372-4d2e0bde-608d-11e7-9420-f19b997b434f.png)

**Comment by aloneguid** [comment]
looks awesome, same as Jupyter would display it. I can only see a potential problem when column value doesn't fit in column width. Maybe a parameter to limit output columns by name? Can be another ticket.

**Comment by AndyCross** [comment]
You can see in the timestamp_col that it truncates with an ellipse currently. I'm working on ways to supply options, for instance, what if you have a column called "A" - you'd only ever get 1 char out of it currently.
