### ISSUE TITLE
What would you like Parquet DataSet to support?

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#63]
This is rather a placeholder for wishlist. I know we have some ideas on what we like it to have and how to behave. Like row access, handling large datasets, types transforms etc. Please comment below so we can collect those in one place. Thank you )

Related issues: #67

**Comment by azurecoder** [comment]
1. PagedDatasets collection lazy loaded
2. called ParquetDataFrame encapsulates files and page manifest offset 
3. Contains typed row
4. Implements IEnunerable<ParquetRow>
5. Provider model supports From/ToCsv, From/To Json and From/To XML

**Comment by aloneguid** [comment]
I think we should migrate to row based results, as most workloads deal with rows.

@azurecoder I'm out of ideas how to deal with typed rows though. The only way to do static typing is to declare row type beforehand, sort of like deserialization into a class works, but that will require the client to know dataset types in advance.

IEnumerable/pages can be supported in reader, we know how to skip rows and only read what's required, this is easy.

**Comment by aloneguid** [comment]
created separate issues for this
