### ISSUE TITLE
Read N number of rows from a specific offset

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#67]
Very large files won't fit in RAM. Can be implemented by skipping rowgroups and certain rows on reader most effectively.

**Comment by AndyCross** [comment]
A few use cases for this, and I'd like supported by the core lib:

* Head n 
  * To be feature compatible with parquet-tools
* Tail n
  * To be feature compatible with parquet-tools
* Pagination at the file level
  * Parq currently creates "folds" after reading the whole file into memory, I would like to be able to request specific ranges , which this should support. 
  * I don't need the reader to be stateful, the consumer can manage the state

**Comment by aloneguid** [comment]
At the moment we can easily support this by passing options to reader. Ideally this should be solved by writing a LINQ provider (then you can use native C# queries) but that's a lot of work. Options will solve the problem and can be used in LINQ. On it.
