### ISSUE TITLE
INT96 - read as raw type

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#75]
`PlainValuesReader.cs`:

```csharp
 [MethodImpl(MethodImplOptions.AggressiveInlining)]
      private static void ReadInt96(byte[] data, SchemaElement schema, IList destination)
      {


#if !SPARK_TYPES
         //var r96 = new List<BigInteger>(data.Length / 12);
#else
         //var r96 = new List<DateTimeOffset?>(data.Length / 12);
#endif

         for (int i = 0; i < data.Length; i += 12)
         {

#if !SPARK_TYPES
            byte[] v96 = new byte[12];
            Array.Copy(data, i, v96, 0, 12);
            var bi = new BigInteger(v96);
#else
            // for the time being we can discard the nanos 
            byte[] v96 = new byte[4];
            byte[] nanos = new byte[8];
            Array.Copy(data, i + 8, v96, 0, 4);
            Array.Copy(data, i, nanos, 0, 8);
            var bi = BitConverter.ToInt32(v96, 0).JulianToDateTime();
            long nanosToInt64 = BitConverter.ToInt64(nanos, 0);
            double millis = (double) nanosToInt64 / 1000000D;
            bi = bi.AddMilliseconds(millis);
#endif
            destination.Add(new DateTimeOffset(bi));

         } 
      }
```

It might be better to always read it as `BigInteger`, and add a method on `Row` class to read alternatively as `DateTimeOffset`. What do you think @azurecoder ?

**Comment by azurecoder** [comment]
Agreed, I don't like conditional compilation statements but I also know that we have to support Spark before the standard. My only observation is that Hive, Impala and Spark support Int96 in this way and they are the only practical use cases of parquet so in essence no-one would be using it for a BigInt. Happy to push this onto a row though and make lazier.

**Comment by aloneguid** [comment]
I was thinking maybe adding it to this one

```csharp
   /// <summary>
   /// Parquet options
   /// </summary>
   public class ParquetOptions
   {
      /// <summary>
      /// When true byte arrays will be treated as UTF-8 strings
      /// </summary>
      public bool TreatByteArrayAsString { get; set; }
   }
```
This way reader now can be forced to utf-8 decode bytearrays, even if they're not annotated, as this is the case with some files I've seen.

And maybe even making datetime default option, but giving users an option to switch it off?

**Comment by azurecoder** [comment]
Seems reasonable. I saw that you added that as a private member in plainreader but didn't expose it.

**Comment by aloneguid** [comment]
It's exposed in `ParquetWriter`, so after creating it you can set `writer.Options.MyOption = true;` etc :)

**Comment by aloneguid** [comment]
Sorry both of them, reader and writer.
