### ISSUE TITLE
Read CSV into DataSet

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#84]
Thinking that because CVS seems to be really popular in data science we could do this. The refeerneced library NetBox already has a good battle tested CSV reader but that only reads strings. 

It might be a good idea to also add type inferring, needs more thought.

Might depend on #78

**Comment by sandy-may** [comment]
@aloneguid I think I did something very similar last week but to DataTable, it had schema inference, will show you Monday and can pick this up

**Comment by aloneguid** [comment]
We already have the code to read into DataSet, it's in tests so needs to be just moved :) How does type inferring work in your case?

**Comment by aloneguid** [comment]
I already have type inferring code, it's a part of NetBox package

**Comment by sandy-may** [comment]
@aloneguid is this done then?

**Comment by aloneguid** [comment]
@sandy-may not yet, it's in a branch if you want to have a look.

**Comment by aloneguid** [comment]
Working on this, still not close to finishing, there are some variations to be covered so it won't make into M2.
