### ISSUE TITLE
Support INT64 writes of TIMESTAMP_MILLIS

### ISSUE THREAD

**Issue by azurecoder** [elastacloud/parquet-dotnet#86]
This is new for Spark 2.2 but is the "true" parquet representation of TIMESTAMP_MILLIS

**Comment by aloneguid** [comment]
I think implementing this first would solve DateTimeOffset write problem immediately in a short term, so we can use it in production.

**Comment by azurecoder** [comment]
Changed the implementation of this to enable support for INT64 seconds from epoch, writer updated
