### ISSUE TITLE
SNAPPY support

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#9]
Support encoding/decoding in SNAPPY for data pages. Dependencies must be managed and .NET Core compatible.

**Comment by aloneguid** [comment]
We might want to scrap this as there is no good SNAPPY library for .NET Core. Until better times. Spark can write files in gzip encoding if that's really required.

**Comment by azurecoder** [comment]
let's keep open maybe we can inspire someone from EC to use some garage time to implement this

**Comment by aloneguid** [comment]
There's this project https://github.com/jeffesp/Snappy.Sharp but it's still "work in progress" since 2012. If we want to implement this it might be an excellent starting point. It doesn't support .NET Core, but shouldn't be too hard to port.

Note, we need to only decompress/compress byte buffers, so snappy streaming is not required for reading, but would add to performance/memory footprint.

**Comment by sandy-may** [comment]
I will have a look at Snappy.Sharp tonight or tomorrow, there is also a NuGet available https://www.nuget.org/packages/Snappy.NET/ will check them both out and see what I can implement

**Comment by dazfuller** [comment]
There's an open pull request on the Snappy.Sharp project which you might find useful Sandy

**Comment by sandy-may** [comment]
owww you are correct! Someone has already posted to Core and released as NuGet https://www.nuget.org/packages/Snappy.Sharp

**Comment by aloneguid** [comment]
Hi guys, don't forget to raise a Pull Request, me & Richard already switched to this approach.

**Comment by aloneguid** [comment]
I looked more into this and it looks like Snappy.Sharp is unstable at the moment. Issues open on GitHub indicate that it doesn't decompress properly is some cases.
